#!/usr/bin/env python3
"""Keeps the OpenCity fluent lint clean.

Many OpenCity messages are looked up with keys built at runtime ("chirp-service-" + kind, enum names, yaml
values on fields without [FluentReference]), which the engine's fluent lint cannot see, so it reports them
as unused. This script reads the lint output, and for every reported key:

  * still referenced by the C# code (literal or a dynamic "prefix-" literal) or by the mod yaml
    -> added to OpenRA.Mods.City/CityFluentKeys.cs, which the lint reads through [FluentReference];
  * referenced nowhere -> printed as dead (and deleted from its .ftl file with --prune).

Keys the lint reports as missing but only CityFluentKeys requires (deleted messages) are dropped from the list.

Usage (from the repository root):
  ./utility.sh city --check-yaml | python3 mods/city/tools/gen_fluent_keys.py [--prune]
"""

import glob
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
OUT = os.path.join(ROOT, "OpenRA.Mods.City", "CityFluentKeys.cs")

HEADER = """#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

namespace OpenRA.Mods.City
{
	/// <summary>
	/// Fluent keys that are only looked up with runtime-built names, listed so the fluent lint sees them.
	/// Generated by mods/city/tools/gen_fluent_keys.py; rerun it after adding such keys.
	/// </summary>
	public static class CityFluentKeys
	{
		[FluentReference]
		public static readonly string[] DynamicKeys =
		[
"""

FOOTER = """		];
	}
}
"""


def read(path):
	with open(path, encoding="utf-8") as f:
		return f.read()


def existing_keys():
	if not os.path.exists(OUT):
		return set()
	body = read(OUT).split("DynamicKeys =", 1)[-1]
	return set(re.findall(r'"([^"]+)"', body))


def references():
	src = "\n".join(read(f) for f in glob.glob(os.path.join(ROOT, "OpenRA.Mods.City", "**", "*.cs"), recursive=True)
		if not f.endswith("CityFluentKeys.cs"))
	literals = set(re.findall(r'"([a-z0-9][a-z0-9.\-]*)"', src))
	literals |= set(re.findall(r'\$"([a-z0-9][a-z0-9\-]*)\{', src))
	yaml = "\n".join(read(f) for f in glob.glob(os.path.join(ROOT, "mods", "city", "**", "*.yaml"), recursive=True))
	words = set(re.findall(r"[a-z0-9][a-z0-9\-]+", yaml))
	return src, literals, words


def is_referenced(key, src, literals, words):
	if key in literals or key in words:
		return True
	parts = key.split("-")
	for i in range(len(parts) - 1, 0, -1):
		prefix = "-".join(parts[:i]) + "-"
		if prefix in literals or '"' + prefix in src:
			return True
	return False


def prune(path, key):
	"""Deletes a message (and its indented continuation/attribute lines) from an ftl file."""
	lines = read(path).split("\n")
	out = []
	skipping = False
	for line in lines:
		if re.match(r"^" + re.escape(key) + r"\s*=", line):
			skipping = True
			continue
		if skipping and (line.startswith((" ", "\t")) and line.strip()):
			continue
		skipping = False
		out.append(line)
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(out))


def main():
	do_prune = "--prune" in sys.argv
	src, literals, words = references()
	keep = existing_keys()
	dead = []
	for line in sys.stdin:
		gone = re.match(r"Warning: Missing key `([^`]+)` in mod ftl files required by CityFluentKeys", line.strip())
		if gone:
			keep.discard(gone.group(1))
			continue

		m = re.match(r"Warning: Unused key `([^`]+)` in city\|(\S+)", line.strip())
		if m:
			key, ftl, attr = m.group(1), m.group(2), None
		else:
			m = re.match(r"Warning: Unused attribute `([^`]+)` of key `([^`]+)` in city\|(\S+)", line.strip())
			if not m:
				continue
			attr, key, ftl = m.group(1), m.group(2), m.group(3)

		if is_referenced(key, src, literals, words):
			keep.add(key if attr is None else key + "." + attr)
		elif (key, ftl) not in dead:
			dead.append((key, ftl))

	for key, ftl in dead:
		print(f"dead: {key} ({ftl})")
		if do_prune:
			prune(os.path.join(ROOT, "mods", "city", ftl), key)

	body = "".join(f'\t\t\t"{k}",\n' for k in sorted(keep))
	with open(OUT, "w", encoding="utf-8") as f:
		f.write(HEADER + body + FOOTER)
	print(f"{len(keep)} dynamic keys listed in {os.path.relpath(OUT, ROOT)}; {len(dead)} dead")


if __name__ == "__main__":
	main()
