#!/usr/bin/env python3
"""
gen_zon.py - OpenCity WP ZON lot art generator (zoned growables, construction,
rubble, zone overlays, signature buildings) + sequences/buildings.yaml.

    python3 mods/city/tools/gen_zon.py                      # write all art + yaml
    python3 mods/city/tools/gen_zon.py --sheet /tmp/s.png [--only res-low,ind] [--fp 2x2,3x2] [--zoom 2]
    python3 mods/city/tools/gen_zon.py --sheet /tmp/s.png --misc   # construction/rubble/overlays/sigs

Every growable image zon/<prefix>-<CX>x<CY>.png holds 40 frames (one row per level):
index = (level-1)*8 + variant, frame size = 32CX x 32(CY+HR), footprint = bottom
32CX x 32CY. Variants 0-3 are the North American theme, 4-7 the European theme (same
massing family as variant-4, EU palettes/roofs/windows). Levels 2 and 4 are upgrades of
tiers 1 and 2 (same building, extra dressing; clearly visible on lots >= 2x2).
Deterministic (seeded). Only imports genworld/pngkit (never edits them).
"""
import os
import sys
from multiprocessing import Pool

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from pngkit import Canvas, save_sheet  # noqa: E402
from gen_zon_base import Lot  # noqa: E402
import gen_zon_res as R  # noqa: E402

MOD = os.path.dirname(HERE)
ZON = os.path.join(MOD, "bits", "world", "zon")
SEQ = os.path.join(MOD, "sequences", "buildings.yaml")

VARIANTS = 8  # 0-3 NA theme, 4-7 EU theme
FOOTPRINTS = ["1x1", "2x1", "1x2", "3x1", "1x3", "2x2", "3x2", "2x3", "3x3", "4x3", "3x4"]


def _zones():
    z = {
        "res-low": (1, "1x1 2x1 1x2 2x2", R.res_low),
        "res-row": (1, "1x2 2x1 1x3 3x1 2x2", R.res_row),
    }
    for mod, entries in _extra_modules():
        z.update(entries)
    return z


def _extra_modules():
    out = []
    for name in ("gen_zon_res2", "gen_zon_com", "gen_zon_ind"):
        try:
            m = __import__(name)
        except ImportError:
            continue
        out.append((m, m.ZONES))
    return out


ZONES = _zones()


def dims(fp):
    cx, cy = fp.split("x")
    return int(cx), int(cy)


def frames_for(prefix, fp):
    hr, _, fn = ZONES[prefix]
    cx, cy = dims(fp)
    return [fn(Lot(prefix, cx, cy, hr, lvl, v)) for lvl in range(1, 6) for v in range(VARIANTS)]


def _job(args):
    kind, a, b = args
    if kind == "grow":
        fr = frames_for(a, b)
        save_sheet(os.path.join(ZON, f"{a}-{b}.png"), fr, cols=VARIANTS)
        return f"{a}-{b}"
    import gen_zon_misc as M
    return M.job(a, b, ZON)


def jobs():
    out = []
    for prefix, (hr, fps, fn) in ZONES.items():
        for fp in fps.split():
            out.append(("grow", prefix, fp))
    try:
        import gen_zon_misc as M
        out += [("misc", a, b) for (a, b) in M.jobs(FOOTPRINTS)]
    except ImportError:
        pass
    return out


def offset(hr):
    return f"0,-{16 * hr}"


def write_yaml():
    legacy = open(SEQ).read().split("\n# ---- WP ZON")[0].rstrip() + "\n"
    t = legacy + "\n# ---- WP ZON lot art (generated by tools/gen_zon.py; do not edit by hand) ----\n"
    t += "# Frames: 40 = 5 levels x 8 variants, index (level-1)*8+variant; variants 0-3 North American,\n"
    t += "# 4-7 European theme. Offset 0,-(16*HR) aligns the frame bottom with the footprint bottom\n"
    t += "# (frame height = 32*(CY+HR)).\n\n"
    for prefix, (hr, fps, fn) in ZONES.items():
        for fp in fps.split():
            t += (f"{prefix}-{fp}:\n\tInherits: ^Growable\n\tidle:\n\t\tFilename: zon/{prefix}-{fp}.png\n"
                  f"\t\tLength: *\n\t\tOffset: {offset(hr)}\n\n")
    try:
        import gen_zon_misc as M
        t += M.yaml(FOOTPRINTS)
    except ImportError:
        pass
    with open(SEQ, "w") as f:
        f.write(t.rstrip() + "\n")


def contact(path, only, fps, zoom):
    """Scratch sheet: per footprint a block of 8 rows (variants; 0-3 NA, 4-7 EU) x 5 columns (levels)."""
    blocks = []
    for prefix in only:
        hr, zfps, fn = ZONES[prefix]
        for fp in zfps.split():
            if fps and fp not in fps:
                continue
            fr = frames_for(prefix, fp)
            blocks.append(fr)
    gap = 4
    W = max(5 * (f[0].w * zoom + gap) for f in blocks) + gap
    Hh = sum(VARIANTS * (f[0].h * zoom + gap) + 3 * gap for f in blocks) + gap
    sheet = Canvas(W, Hh, (104, 148, 78, 255))
    y = gap
    for fr in blocks:
        fw, fh = fr[0].w * zoom, fr[0].h * zoom
        for i, c in enumerate(fr):
            lvl, v = divmod(i, VARIANTS)
            sheet.blit(c.scale(zoom) if zoom > 1 else c, gap + lvl * (fw + gap), y + v * (fh + gap))
        y += VARIANTS * (fh + gap) + 3 * gap
        sheet.rect(0, y - 2 * gap, W, 2, (40, 60, 40, 255))
    sheet.save(path)


def arg(name, default=None):
    return sys.argv[sys.argv.index(name) + 1] if name in sys.argv else default


def main():
    if "--sheet" in sys.argv:
        path = arg("--sheet")
        if "--misc" in sys.argv:
            import gen_zon_misc as M
            M.contact(path, int(arg("--zoom", "2")))
            return
        only = arg("--only", ",".join(ZONES)).split(",")
        fps = arg("--fp", "")
        contact(path, only, fps.split(",") if fps else None, int(arg("--zoom", "2")))
        return
    os.makedirs(ZON, exist_ok=True)
    with Pool(min(16, os.cpu_count() or 4)) as p:
        done = p.map(_job, jobs(), chunksize=1)
    write_yaml()
    print(f"gen_zon: wrote {len(done)} images + {os.path.relpath(SEQ, MOD)}")


if __name__ == "__main__":
    main()
