#!/usr/bin/env python3
"""
gen_svc.py - art generator of the services work package.

    python3 mods/city/tools/gen_svc.py [--sheet /tmp/svc-contact.png]

Writes
  bits/world/svc/*.png          new service buildings, rubble and effects (fire, garbage piles)
  bits/chrome/buildicons.png    build-menu icon atlas for every placeable (services, utilities and stand-ins for other WPs)
  chrome-buildings.yaml         regions of that atlas
  sequences/services.yaml       sequences of all services (existing art in bits/world/, new art in bits/world/svc/)

It imports the drawing helpers of genworld.py (and uses its existing service sprites for their icons) but never writes
anything genworld.py owns, except that it replaces the build icon atlas, chrome-buildings.yaml and services.yaml that
genworld.py also writes: do not run genworld.py's main() after this.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import genworld as gw  # noqa: E402
import gen_svc_a  # noqa: E402
import gen_svc_b  # noqa: E402
import gen_svc_c  # noqa: E402
import gen_svc_d  # noqa: E402
import gen_svc_e  # noqa: E402
from pngkit import Canvas, save_sheet, save_atlas  # noqa: E402

MOD = gw.MOD
SVC = os.path.join(gw.WORLD, "svc")
CHROME = gw.CHROME

TINT = {
    "powerplant-gas": "F2B84B", "hydro-dam": "F2B84B", "powerplant-nuclear": "F2B84B", "waterpump-large": "4FA3E8",
    "landfill": "8A7355", "incinerator": "8A7355", "recycling": "5DBB63",
    "hospital": "3FC1A5", "cemetery": "8E96A0", "crematorium": "8E96A0",
    "highschool": "F29A4B", "college": "F29A4B", "university": "F29A4B",
    "policebox": "4C7BE0", "police-hq": "4C7BE0", "prison": "6E7882", "firehouse": "E0534A",
    "sportsfield": "5DBB63", "postoffice": "E8C547", "sortingcenter": "E8C547",
    "telecom-mast": "9B7BE0", "telecom-tower": "9B7BE0", "cityhall": "C9A52E", "welfare": "E8467C",
    "farm-hub": "C9B45A", "forestry-hub": "5DA060", "quarry-hub": "A59D8E", "mine-hub": "8E8A80", "oil-hub": "6B6B78",
    "medevac-helipad": "3FC1A5", "fire-helipad": "E0534A", "firewatch": "E0534A",
    "busdepot": "2E9E6A", "busstop": "2E9E6A", "transformer": "F2B84B", "sewage-outlet": "4FA3E8", "treatment-plant": "4FA3E8",
}

# Frames that are used only for build icons (not placed as actors by this work package).
ICON_ONLY = gen_svc_d.STANDINS


def contact_sheet(path, groups):
    pad = 4
    cells = []
    for name, c in groups:
        cells.append((name, c))
    cols = 6
    cw = max(c.w for _, c in cells) + pad
    ch = max(c.h for _, c in cells) + pad
    rows = (len(cells) + cols - 1) // cols
    sheet = Canvas(cw * cols, ch * rows, (92, 120, 84, 255))
    for i, (name, c) in enumerate(cells):
        sheet.blit(c, (i % cols) * cw + pad // 2, (i // cols) * ch + pad // 2)
    sheet.save(path)


def main():
    os.makedirs(SVC, exist_ok=True)
    existing = gw.build_services()
    new = {}
    for mod in (gen_svc_a, gen_svc_b, gen_svc_c, gen_svc_e):
        new.update(mod.build())

    for name, (frames, tick, size) in new.items():
        save_sheet(os.path.join(SVC, name + ".png"), frames)

    fire = gen_svc_d.fire_frames()
    piles = gen_svc_d.pile_frames()
    save_sheet(os.path.join(SVC, "fire.png"), fire)
    save_sheet(os.path.join(SVC, "pile.png"), piles)
    save_sheet(os.path.join(SVC, "heli.png"), gen_svc_e.heli_frames())

    # Build icons for every placeable (rubble is not placeable).
    gw.ICON_TINT.update(TINT)
    regions = {}
    for name, (frames, tick, size) in list(existing.items()) + [(k, v) for k, v in new.items() if k != "rubble"]:
        regions[name] = gw.build_icon(name, frames[0], size)
    for name, fn in ICON_ONLY.items():
        regions[name] = gw.build_icon(name, fn(), 2)
    placed = save_atlas(os.path.join(CHROME, "buildicons.png"), regions, width=512)
    with open(os.path.join(MOD, "chrome-buildings.yaml"), "w") as f:
        f.write("# Build-menu icons (48x48), one region per CityPlaceable actor. Generated by tools/gen_svc.py.\n")
        f.write("# Includes stand-in icons for the placeables of other work packages (hubs, depots, utilities).\n")
        f.write("city-buildicons:\n\tImage: buildicons.png\n\tRegions:\n")
        for name in sorted(placed):
            x, y, w, h = placed[name]
            f.write(f"\t\t{name}: {x}, {y}, {w}, {h}\n")

    t = "# Services. 1x1 frames 32x64, 2x2 frames 64x96, 3x3 frames 96x128 (footprint = bottom square). Generated by tools/gen_svc.py.\n"
    t += "# Art of the original services lives in bits/world/, new art in bits/world/svc/.\n"
    for name, (frames, tick, size) in existing.items():
        t += f"{name}:\n\tidle:\n\t\tFilename: {name}.png\n\t\tLength: *\n"
        if tick:
            t += f"\t\tTick: {tick}\n"
        t += "\t\tOffset: 0,-16\n\n"
    for name, (frames, tick, size) in new.items():
        t += f"{name}:\n\tidle:\n\t\tFilename: svc/{name}.png\n\t\tLength: *\n"
        if tick:
            t += f"\t\tTick: {tick}\n"
        t += "\t\tOffset: 0,-16\n\n"
    t += "# Effects drawn by ServiceEffects: flames of burning buildings (4 frames, anchored at the bottom centre) and garbage heaps.\n"
    t += "svc-fire:\n\tidle:\n\t\tFilename: svc/fire.png\n\t\tLength: *\n\t\tTick: 90\n\t\tOffset: 0,-8\n\n"
    t += "svc-heli:\n\tidle:\n\t\tFilename: svc/heli.png\n\t\tLength: *\n\t\tTick: 2\n\t\tOffset: 0,-24\n\n"
    t += "svc-pile:\n\tsmall:\n\t\tFilename: svc/pile.png\n\t\tStart: 0\n\t\tLength: 1\n\t\tOffset: 0,-4\n"
    t += "\tmedium:\n\t\tFilename: svc/pile.png\n\t\tStart: 1\n\t\tLength: 1\n\t\tOffset: 0,-4\n"
    t += "\tlarge:\n\t\tFilename: svc/pile.png\n\t\tStart: 2\n\t\tLength: 1\n\t\tOffset: 0,-4\n"
    with open(os.path.join(MOD, "sequences", "services.yaml"), "w") as f:
        f.write(t.rstrip() + "\n")

    if "--sheet" in sys.argv:
        groups = [(n, v[0][0]) for n, v in new.items()] + [(n, fn()) for n, fn in ICON_ONLY.items()]
        contact_sheet(sys.argv[sys.argv.index("--sheet") + 1], groups)
        icons = sorted(regions.items())
        contact_sheet(sys.argv[sys.argv.index("--sheet") + 1].replace(".png", "-icons.png"), icons)
    print(f"gen_svc: {len(new)} service sprites, {len(regions)} icons")


if __name__ == "__main__":
    main()
