#!/usr/bin/env python3
"""gen_zon_rules.py - writes mods/city/rules/growables.yaml (lot archetypes, zone templates, legacy decoration, rubble, signatures).

The zone numbers (densities, upkeep, rent factors) live here; edit and rerun:  python3 mods/city/tools/gen_zon_rules.py
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ZONES = [
    # prefix, enum, tpl, footprints
    ("res-low", "ResidentialLow", "ResLow", ["1x1", "2x1", "1x2", "2x2"]),
    ("res-row", "ResidentialRow", "ResRow", ["1x2", "2x1", "1x3", "3x1", "2x2"]),
    ("res-med", "ResidentialMedium", "ResMed", ["2x2", "3x2", "2x3", "3x3"]),
    ("res-high", "ResidentialHigh", "ResHigh", ["2x2", "3x2", "2x3", "3x3"]),
    ("res-lowrent", "ResidentialLowRent", "ResLowRent", ["2x2", "3x2", "2x3"]),
    ("res-mixed", "ResidentialMixed", "ResMixed", ["2x2", "3x2", "2x3"]),
    ("com-low", "CommercialLow", "ComLow", ["1x1", "2x1", "1x2", "2x2"]),
    ("com-high", "CommercialHigh", "ComHigh", ["2x2", "3x2", "2x3", "3x3", "4x3", "3x4"]),
    ("off", "Office", "Office", ["1x1", "2x1", "1x2", "2x2", "2x3", "3x2", "3x3"]),
    ("off-high", "OfficeHigh", "OfficeHigh", ["2x2", "3x2", "2x3", "3x3"]),
    ("ind", "Industrial", "Ind", ["1x1", "2x2", "3x2", "2x3", "3x3", "4x3", "3x4"]),
    ("warehouse", "Warehouse", "Warehouse", ["3x2", "2x3", "3x3", "4x3", "3x4"]),
]
LEGACY = ["res-low", "res-high", "com-low", "com-high", "ind", "off"]
ALLSHAPES = ["1x1", "2x1", "1x2", "3x1", "1x3", "2x2", "3x2", "2x3", "3x3", "4x3", "3x4"]

out = []
w = out.append
w("# GENERATED by tools/gen_zon_rules.py (edit the script, then rerun it). Growable (zoned) buildings, owned by the zoning WP (ZON), design/04-zoning-buildings.md.")
w("#")
w("# One actor per zone and footprint, named <prefix>-<W>x<D> (ZoneGrowth builds its lot catalogue from these names: a rectangular")
w("# shape needs both orientations). Levels 1-5 are state on the actor (GrowableBuilding.Level), never separate actors.")
w("# The numbers live in the zone templates (^Zone*). The legacy actors res-low-1..3 etc. only exist for old maps (shellmap).")
w("")
w("^Growable:")
w("\tInherits: ^CityStructure")
w("\tInherits@shape: ^1x1Shape")
w("\t-WithSpriteBody:")
w("\tWithGrowableSprite:")
w("\t\tConstructionImage: construction")
w("\t\tConstructionSequence: small")
w("\t\tSequence: idle")
w("\tBulldozable:")
w("\t\tRefundPercent: 0")
w("")
w("^Lot:")
w("\tInherits: ^CityStructure")
w("\t-WithSpriteBody:")
w("\tWithGrowableSprite:")
w("\t\tConstructionImage: zon-construction")
w("\t\tSequence: idle")
w("\tBulldozable:")
w("\t\tRefundPercent: 0")
w("")
for s in ALLSHAPES:
    cx, cy = map(int, s.split("x"))
    w(f"^Lot{s}:")
    w("\tBuilding:")
    w(f"\t\tDimensions: {cx},{cy}")
    w("\t\tFootprint: " + " ".join("x" * cx for _ in range(cy)))
    w("\tHitShape:")
    w("\t\tUseTargetableCellsOffsets: true")
    w("\t\tType: Rectangle")
    w(f"\t\t\tTopLeft: -{cx * 512}, -{cy * 512}")
    w(f"\t\t\tBottomRight: {cx * 512}, {cy * 512}")
    w("\tWithGrowableSprite:")
    w(f"\t\tConstructionSequence: s{s}")
    w("")


def zone(tpl, enum, tip, **kw):
    w(f"^Zone{tpl}:")
    w("\tTooltip:")
    w(f"\t\tName: actor-lot-{tip}.name")
    w("\tGrowableBuilding:")
    w(f"\t\tZone: {enum}")
    for k, v in kw.items():
        if k == "pollution":
            continue
        if isinstance(v, bool):
            v = "true" if v else "false"
        if isinstance(v, list):
            v = ", ".join(map(str, v))
        w(f"\t\t{k}: {v}")
    w("\tCityBuilding:")
    w(f"\t\tZone: {enum}")
    if "pollution" in kw:
        w(f"\t\tPollution: {kw['pollution']}")
    w("")


zone("ResLow", "ResidentialLow", "res-low", HouseholdsPerCellMilli=1000, SingleHousehold=True, ResidentsPerHousehold=4, HomeBusinessJobs=1,
     JobMix=[0, 20, 40, 30, 10], UpkeepPerCell=3, RentZoneFactor=6, AreaByLandValue=True, PowerPerCellMilli=450, WaterPerCellMilli=450)
zone("ResRow", "ResidentialRow", "res-row", HouseholdsPerCellMilli=1000, ResidentsPerHousehold=3, UpkeepPerCell=4, RentZoneFactor=4,
     PowerPerCellMilli=1000, WaterPerCellMilli=1000)
zone("ResMed", "ResidentialMedium", "res-med", HouseholdsPerCellMilli=1500, ResidentsPerHousehold=3, UpkeepPerCell=4, RentZoneFactor=4,
     RentSpacePercent=150, PowerPerCellMilli=1200, WaterPerCellMilli=1200)
zone("ResHigh", "ResidentialHigh", "res-high", HouseholdsPerCellMilli=4500, ResidentsPerHousehold=3, UpkeepPerCell=6, RentZoneFactor=3,
     RentSpacePercent=250, PowerPerCellMilli=2000, WaterPerCellMilli=2000, SpawnLevel2LandValue=70)
zone("ResLowRent", "ResidentialLowRent", "res-lowrent", StudentHousingPercent=60, HouseholdsPerCellMilli=4000, ResidentsPerHousehold=2, UpkeepPerCell=4, RentZoneFactor=2,
     RentSpacePercent=150, PowerPerCellMilli=1500, WaterPerCellMilli=1500)
zone("ResMixed", "ResidentialMixed", "res-mixed", HouseholdsPerCellMilli=1500, ResidentsPerHousehold=3, JobsPerCellMilli=2000, JobMix=[30, 50, 20, 0, 0],
     UpkeepPerCell=5, RentZoneFactor=5, RentSpacePercent=150, PowerPerCellMilli=1500, WaterPerCellMilli=1200)
zone("ComLow", "CommercialLow", "com-low", LodgingPerCellMilli=500, JobsPerCellMilli=3000, JobMix=[25, 50, 25, 0, 0], UpkeepPerCell=3, RentZoneFactor=5,
     PowerPerCellMilli=1000, WaterPerCellMilli=1000)
zone("ComHigh", "CommercialHigh", "com-high", LodgingPerCellMilli=1500, JobsPerCellMilli=7000, JobMix=[15, 40, 35, 10, 0], UpkeepPerCell=4, RentZoneFactor=6, LandValueBonus=10,
     PowerPerCellMilli=2000, WaterPerCellMilli=1000, SpawnLevel2LandValue=70)
zone("Office", "Office", "off", JobsPerCellMilli=7500, JobMix=[0, 10, 35, 40, 15], UpkeepPerCell=4, RentZoneFactor=8,
     PowerPerCellMilli=1500, WaterPerCellMilli=1000, SpawnLevel2LandValue=70)
zone("OfficeHigh", "OfficeHigh", "off-high", JobsPerCellMilli=10000, JobMix=[0, 5, 30, 45, 20], UpkeepPerCell=5, RentZoneFactor=9, RentSpacePercent=120,
     PowerPerCellMilli=2000, WaterPerCellMilli=1200, SpawnLevel2LandValue=70)
zone("Ind", "Industrial", "ind", StoragePerCellMilli=2000, JobsPerCellMilli=5000, JobMix=[45, 40, 15, 0, 0], UpkeepPerCell=2, RentZoneFactor=3, LandValueCap=60,
     PowerPerCellMilli=3000, WaterPerCellMilli=2000, pollution=40)
zone("Warehouse", "Warehouse", "warehouse", StoragePerCellMilli=20000, JobsPerCellMilli=1000, JobMix=[60, 35, 5, 0, 0], UpkeepPerCell=1, RentZoneFactor=2, LandValueCap=60,
     PowerPerCellMilli=800, WaterPerCellMilli=300, pollution=10)

w("# ---- lot archetypes: <prefix>-<W>x<D> ----")
w("")
for prefix, enum, tpl, shapes in ZONES:
    for s in shapes:
        w(f"{prefix}-{s}:")
        w("\tInherits: ^Lot")
        w(f"\tInherits@shape: ^Lot{s}")
        w(f"\tInherits@zone: ^Zone{tpl}")
    w("")


w("# ---- signature buildings (design 3.8): free, once per city, unlocked by rules (SignatureUnlocks), act as a level 5 lot plus a bonus ----")
w("")
SIGS = [
    ("sig-villa", "ResLow", "ResidentialLow", ["ZoneCells:ResidentialLow:60", "Happiness:60"], dict(WellBeing=4, WellBeingRadius=12)),
    ("sig-garden-row", "ResRow", "ResidentialRow", ["ZoneCells:ResidentialRow:40"], dict(WellBeing=3, WellBeingRadius=10)),
    ("sig-sky-tower", "ResHigh", "ResidentialHigh", ["Level5Count:ResidentialHigh:6"], dict(WellBeing=6, WellBeingRadius=14)),
    ("sig-bazaar", "ComLow", "CommercialLow", ["ZoneCells:CommercialLow:80"], dict(Attractiveness=10)),
    ("sig-mall", "ComHigh", "CommercialHigh", ["Level5Count:CommercialHigh:8"], dict(Attractiveness=20)),
    ("sig-glass-hub", "Office", "Office", ["Level5Count:Office:6", "ServiceBuilt:school:1"], dict(EfficiencyPercent=2)),
    ("sig-fuel-plant", "Ind", "Industrial", ["Level5Count:Industrial:6"], dict(EfficiencyPercent=2, PollutionReductionPercent=5, WellBeingRadius=12)),
]
for name, tpl, enum, rules, bonus in SIGS:
    w(f"{name}:")
    w("\tInherits: ^Lot")
    w("\tInherits@shape: ^Lot3x3")
    w(f"\tInherits@zone: ^Zone{tpl}")
    w("\tTooltip:")
    w(f"\t\tName: actor-{name}.name")
    w("\tGrowableBuilding:")
    w("\t\tLevel: 5")
    w("\t\tFixedLevel: true")
    w("\t\tAreaByLandValue: false")
    w("\tSignatureBuilding:")
    w("\t\tUnlock: " + ", ".join(rules))
    w(f"\t\tDescription: actor-{name}.description")
    for k, v in bonus.items():
        w(f"\t\t{k}: {v}")
    w("\tCityPlaceable:")
    w("\t\tCost: 0")
    w("\t\tCategory: signature")
    w("\t\tUnlockPopulation: 1000000")
    w(f"\t\tDescription: actor-{name}.description")
    w("")

w("# ---- legacy decoration: fixed-level 1x1 buildings of old maps (shellmap). Art is the old 32x64 set. ----")
w("")
tplof = {p: t for p, e, t, s in ZONES}
for prefix in LEGACY:
    for lvl in (1, 2, 3):
        w(f"{prefix}-{lvl}:")
        w("\tInherits: ^Growable")
        w(f"\tInherits@zone: ^Zone{tplof[prefix]}")
        w("\tTooltip:")
        w(f"\t\tName: actor-{prefix}-{lvl}.name")
        w("\tGrowableBuilding:")
        w(f"\t\tLevel: {[1, 3, 5][lvl - 1]}")
        w("\tWithGrowableSprite:")
        w("\t\tLevels: 1")
        w("")

w("# ---- rubble of collapsed buildings (blocks the lot, bulldoze for free, vanishes after a while) ----")
w("")
w("^RubbleBase:")
w("\tInherits: ^CityStructure")
w("\t-CityBuilding:")
w("\t-PollutionSource:")
w("\t-CityProblems:")
w("\t-AppearsOnRadar:")
w("\t-MapEditorData:")
w("\tRenderSprites:")
w("\t\tImage: zon-rubble")
w("\tTooltip:")
w("\t\tName: actor-rubble.name")
w("\tRubble:")
w("\t\tTicks: 4800")
w("\tBulldozable:")
w("\t\tRefundPercent: 0")
w("")
for s in ALLSHAPES:
    w(f"rubble-{s}:")
    w("\tInherits: ^RubbleBase")
    w(f"\tInherits@shape: ^Lot{s}")
    w("\t-WithGrowableSprite:")
    w("\tWithSpriteBody:")
    w(f"\t\tSequence: s{s}")
    w("")

open(os.path.join(ROOT, "rules", "growables.yaml"), "w").write("\n".join(out).rstrip() + "\n")
print(len(out), "lines")
