"""City HUD chrome (cityicons atlas + chrome-city.yaml), loadscreen/icons and cursors glue for genui."""

import os
from uidraw import Atlas, G
from uitheme import *  # noqa: F401,F403
from uistyle import marble, leather, framed_panel, stylize
import uiorder

DIM_FRAME = ((150, 118, 88, 255), (104, 80, 58, 255), (64, 46, 34, 255))
HL_FRAME = ((255, 226, 140, 255), (236, 150, 50, 255), (140, 70, 20, 255))


def styled(fn):
    def draw(g):
        fn(g)
        stylize(g, outline=1.0, bevel=1.3)
    return draw


def styled_small(fn):
    """Render the 32px recipe at half size (16px at 1x) with a one-device-pixel outline."""
    def draw(g):
        sub = G(32, 32, g.s / 2.0)
        fn(sub)
        stylize(sub, outline=2.0, bevel=2.0)
        g.cv.blit(sub.cv, 0, 0)
    return draw


def button(base, frame=None, invert=False, thick=2.0):
    return lambda g: framed_panel(g, 4.5, leather(base), thickness=thick, invert=invert, frame=frame)


def build_city(scales, mod, icons, aliases, save_atlas):
    atlas = Atlas(512)
    for n, fn in icons:
        atlas.add('icon:' + n, 32, 32, styled(fn))
    for n, fn in icons:
        atlas.add('small:' + n, 16, 16, styled_small(fn))

    for k in uiorder.ORDER_KINDS:
        for suf, st in uiorder.ORDER_STATES:
            atlas.add('order:' + k + suf, 34, 35, uiorder.draw_tile(k, st))

    panels = []   # name, w, h, corner

    def pan(name, w, h, c, draw):
        panels.append((name, w, h, c))
        atlas.add(name, w, h, draw)

    pan('city-panel', 32, 32, 10, lambda g: framed_panel(g, 7, marble((70, 14, 11, 242), (140, 40, 24), 1), 3.0))
    pan('city-toolbar', 32, 32, 10, lambda g: framed_panel(g, 8, marble((46, 9, 8, 246), (110, 30, 20), 2, contrast=0.8), 3.5))
    pan('city-tooltip', 16, 16, 5, lambda g: framed_panel(g, 3.5, lambda x, y: (22, 9, 7, 248), 1.6))
    pan('city-button', 20, 20, 6, button((112, 58, 20)))
    pan('city-button-hover', 20, 20, 6, button((150, 84, 32)))
    pan('city-button-pressed', 20, 20, 6, button((70, 36, 13), invert=True))
    pan('city-button-disabled', 20, 20, 6, button((78, 62, 50), frame=DIM_FRAME))
    pan('city-button-highlighted', 20, 20, 6, button((206, 104, 24), frame=HL_FRAME))
    pan('city-button-highlighted-hover', 20, 20, 6, button((236, 134, 40), frame=HL_FRAME))
    pan('city-button-highlighted-pressed', 20, 20, 6, button((146, 68, 14), frame=HL_FRAME, invert=True))
    pan('city-button-highlighted-disabled', 20, 20, 6, button((112, 76, 46), frame=DIM_FRAME))

    placed = save_atlas(atlas, 'cityicons')
    out = ['^CityIcons:', '\tImage: cityicons.png', '\tImage2x: cityicons-2x.png', '\tImage3x: cityicons-3x.png', '']
    for coll, prefix in (('city-icons', 'icon:'), ('city-icons-small', 'small:')):
        out += [coll + ':', '\tInherits: ^CityIcons', '\tRegions:']
        names = [n for n, _ in icons]
        for n in sorted(names + list(aliases)):
            src = aliases.get(n, n)
            x, y, w, h = placed[prefix + src]
            out.append('\t\t%s: %d, %d, %d, %d' % (n, x, y, w, h))
        out.append('')
    out += ['city-order-icons:', '\tInherits: ^CityIcons', '\tRegions:']
    for k in uiorder.ORDER_KINDS:
        for suf, st in uiorder.ORDER_STATES:
            x, y, w, h = placed['order:' + k + suf]
            out.append('\t\t%s: %d, %d, %d, %d' % (k + suf, x, y, w, h))
    out.append('')
    for name, w, h, c in panels:
        x, y, _, _ = placed[name]
        out += [name + ':', '\tInherits: ^CityIcons',
                '\tPanelRegion: %d, %d, %d, %d, %d, %d, %d, %d' % (x, y, c, c, w - 2 * c, h - 2 * c, c, c), '']
    with open(os.path.join(mod, 'chrome-city.yaml'), 'w') as f:
        f.write('# GENERATED by tools/genui.py - do not edit by hand.\n'
                '# Dune 2000 style: beveled gold/bronze glyphs with dark outlines, marble + bronze frames, leather buttons.\n'
                '# city-icons: 32x32 glyphs, city-icons-small: the same names at 16x16. Contract set + extras:\n'
                '#   demand info warning traffic pollution tax up down check plus minus,\n'
                '#   aliases speed-1/2/3 (= play/fast/faster) and electricity (= power).\n'
                '# More (tools/uicityicons2.py):\n'
                '#   roads: road-street road-gravel road-avenue road-boulevard road-highway\n'
                '#   road tools: road-draw road-oneway road-replace road-signal road-roundabout road-interchange\n'
                '#   utilities: power-line pipe transformer battery sewage networks\n'
                '#   zones: zone-res-row zone-res-med zone-res-mixed zone-res-lowrent zone-off-high zone-warehouse\n'
                '#   industry: industry hub-farm hub-forestry hub-quarry hub-mine hub-oil area-paint area-clear\n'
                '#   transit: transit bus taxi tram metro train bus-stop bus-depot line\n'
                '#   services: garbage deathcare comms post admin\n'
                '#   panels/stats: stats chirper production policies progression districts tiles xp dev-point permit\n'
                '#     loan fee citizen home work school tourist hotel\n'
                '#   misc: lock eye arrow-left arrow-right follow locate\n'
                '# city-order-icons: 34x35 D2k-style order tiles, each + -disabled / -active:\n'
                '#   bulldoze infoviews budget stats chirper production policies progression districts tiles transit.\n'
                '# Panels (9-slice): city-panel city-toolbar city-tooltip city-button[-hover|-pressed|-disabled]\n'
                '# and city-button-highlighted[-hover|-pressed|-disabled].\n' + '\n'.join(out).rstrip('\n') + '\n')


def build_loadscreen_and_icons(scales, mod):
    import uilogo
    uilogo.build(scales, mod)


def build_cursors(mod):
    import uicursors
    uicursors.build(mod)
