"""iso_export_life - LIFE art for the game: vehicles, people, FX sheets (MOV adopts them), status icons, fire, garbage
heaps and the service helicopter (sequences/misc.yaml).

    ISO_EXPORT_PROCS=4 python3 mods/city/tools/iso_export.py life

Outputs (bits/world/iso/life/):  vehicles/*.png  people/*.png  fx/*.png  icons/*.png  README
Documentation for MOV (the exact vehicles.yaml + transit.yaml content):  design/iso/life-sequences.yaml
Sequences written here: sequences/misc.yaml (envicons, envlights (unchanged), svc-fire, svc-heli, svc-pile).
Parts: iso_export_life_vehicles / _people / _icons / _fx.
"""
import os

import iso_export_lib as L
from iso_export_lib import SeqFile
import iso_export_life_vehicles as VEH
import iso_export_life_people as PEO
import iso_export_life_icons as ICO
import iso_export_life_fx as FX

DOC_HEADER = """
Vehicle and people sequences for MOV (sequences/vehicles.yaml + sequences/transit.yaml). Paste what you need.
Sheets: bits/world/iso/life/{vehicles,people}/*.png. Every image keeps today's name where one existed
(car-a..d, truck, van, bus, taxi, tram, train, traincar, garbage, ambulance, firetruck, policecar, hearse, pedestrian)
and LIFE's new models are added under their model names.
Facings: -8. Frames are clockwise from world north: 0 N (-Y, screen up-right), 1 NE, 2 E (+X, screen down-right),
3 SE, 4 S, 5 SW, 6 W, 7 NW; the game's WAngle yaw feeds GetSprite(frame, yaw) as for any Facings: -8 sequence.
Animated sequences are facing-major: frame = facing * Length + anim. Anchor = ground centre (Offset 0,0).
Tick is milliseconds per frame (suggestion); the sim code usually picks frames itself.
"""

MISC_HEADER = """
Status icons, fire, garbage heaps and the service helicopter (generated by tools/iso_export_life.py).
envicons.tiles   8 frames, one per ProblemTier (0 Minimal grey, 1 Info blue, 2 Problem yellow, 3 Warning orange,
                 4 Major red, 5 Error dark red, 6 Fatal black, 7 Good green): an empty thought bubble.
envicons.glyphs  24 frames, frame = CityProblem - 1 (0 NoPower ... 23 Flooded): the glyph on a transparent bubble
                 canvas. Tile and glyph frames share one anchor (the bubble body centre): draw both at the same point.
envicons.extras  9 more glyphs (NoEducation, NoHealthcare, NoPolice, NoFireCover, NoPowerBuild, LowLandValue,
                 Homeless, DeadBody, NoFuel), not wired to a CityProblem yet.
svc-fire         idle = stage 2 (6 frames); stage1..stage4 (6 frames each: window, medium, roof, burnt out), heap
                 (4 frames, burning garbage). Anchor = footprint ground centre (bottom centre of the sprite).
svc-pile         small, medium, large garbage heaps, anchor = ground centre of the heap.
svc-heli         idle = medevac helicopter, SE facing, 4 rotor frames, body 24 px above its ground anchor with the
                 shadow on the ground (ServiceEffects keeps working unchanged); fly / fly-fire = 8 facings x 4 rotor
                 frames (Facings: -8, frame = facing * 4 + rotor), same lift. For real height use images
                 heli-medevac / heli-fire (ground anchored, separate `shadow`) from life-sequences.yaml.
envlights        unchanged (old env/lights.png, replaced by BLD later).
"""


def veh_seqs(sf, image, model, S):
    for seq, fn, start, length, comment in S.models[model]:
        tick = None
        if seq.startswith("siren"):
            tick = 150
        elif seq.startswith("beacon"):
            tick = 300
        elif length > 1:
            tick = 40          # rotor / propeller frames
        sf.seq(image, seq, fn, length=length, start=start or None, comment=comment, Facings=-8, Tick=tick)


def people_seqs(sf, image, entries):
    for seq, fn, start, length, comment, facings in entries:
        tick = 120 if length > 1 else None
        sf.seq(image, seq, fn, length=length, start=start or None, comment=comment,
               Facings=-8 if facings == 8 else None, Tick=tick)


def readme(S, people, icons, fire, fx_rows):
    out = ["LIFE art exported by tools/iso_export_life.py (do not edit). Sheets are PngSheets: tightly cropped frames,",
           "Frame[i] = x,y,w,h;ox,oy, anchor = ground centre / emitter / feet as stated. Filenames are relative to",
           "bits/world (iso/life/...). Ready-to-paste sequences: design/iso/life-sequences.yaml.",
           "",
           "FACINGS (vehicles, people with 'facing 8')",
           "  8 facings clockwise from world north: 0 N (-Y, screen up-right), 1 NE, 2 E (+X, down-right), 3 SE,",
           "  4 S (+Y, down-left), 5 SW, 6 W (-X, up-left), 7 NW (screen up). Sequence: Facings: -8.",
           "  Frame = facing * Length + anim. Anchor = ground centre of the vehicle.",
           "  Cars (+ delivery-van) sheets hold colour sets: frames 0-7 = default (red), then 8 per colour in the order",
           "  " + ", ".join(VEH.COLOUR_NAMES) + " (sequence per colour: Start = 8 * (index + 1), Length 1).",
           "  Lit / beam / siren-lit / beacon-lit sheets use the day canvas and anchor, so draw them at the same position:",
           "  -lit = lit lamps only (no night tint), -beam = dithered road beam (additive).",
           "",
           "VEHICLES (iso/life/vehicles/<file>)"]
    for cat, models in VEH.ORDER:
        out.append("  [%s]" % cat)
        for m in models:
            names = [a for a, b in VEH.LEGACY.items() if b == m]
            out.append("  %s%s  (anchor %d,%d in a %dx%d design canvas)" % (
                m, "  = legacy image " + ", ".join(names) if names else "", S.size[m][2], S.size[m][3], S.size[m][0], S.size[m][1]))
            for seq, fn, start, length, comment in S.models[m]:
                out.append("      %-11s %s  Start %d Length %d%s" % (seq, os.path.basename(fn), start, length,
                                                                    "  # " + comment if comment else ""))
    out += ["", "PEOPLE (iso/life/people/<file>), anchor = feet (bottom row, canvas centre)",
            "  Design art has 4 directions (N E S W); facing 8 sequences map NE->N, SE->E, SW->S, NW->W.",
            "  Birds and benches have no facings."]
    for image, entries in people.items():
        out.append("  %s" % image)
        for seq, fn, start, length, comment, facings in entries:
            out.append("      %-10s %s  Start %d Length %d%s%s" % (seq, os.path.basename(fn), start, length,
                                                                 "  facing 8" if facings == 8 else "",
                                                                 "  # " + comment if comment else ""))
    out += ["", "ICONS AND SERVICE EFFECTS: see sequences/misc.yaml header (iso/life/icons/*.png)",
            "  problem-tiles.png 8, problem-glyphs.png 24, problem-extras.png 9, fire.png 28 (stage1-4 x 6, heap 4),",
            "  pile.png 3, heli.png 64 (medevac then fire; facing-major, 4 rotor frames).",
            "", "FX (iso/life/fx/<name>.png): name, frames, anchor, suggested Tick ms (0 static), blend"]
    for name, n, anchor, tick, blend, comment in fx_rows:
        a = anchor if isinstance(anchor, str) else "pixel %d,%d" % anchor
        out.append("  %-18s %2d frames  anchor %-9s Tick %-3s %-8s %s" % (name + ".png", n, a, tick or "-", blend, comment))
    return "\n".join(out) + "\n"


def export():
    S, results = VEH.export_vehicles()
    people, _ = PEO.export_people()
    icons = ICO.export_icons()
    fire = ICO.export_fire_piles()
    heli = ICO.export_heli(results)
    fx_rows = FX.export_fx()

    # design/iso/life-sequences.yaml: what MOV pastes into vehicles.yaml / transit.yaml
    doc = SeqFile("life-sequences.yaml", DOC_HEADER)
    for cat, models in VEH.ORDER:
        for m in models:
            veh_seqs(doc, m, m, S)
            for legacy, target in VEH.LEGACY.items():
                if target == m:
                    veh_seqs(doc, legacy, m, S)
    for image, entries in people.items():
        people_seqs(doc, image, entries)
    L.write_if_changed(os.path.join(L.DESIGN, "life-sequences.yaml"), doc.text())

    # sequences/misc.yaml
    sf = SeqFile("misc.yaml", MISC_HEADER)
    sf.seq("envicons", "tiles", icons["tiles"][0], length=icons["tiles"][1])
    sf.seq("envicons", "glyphs", icons["glyphs"][0], length=icons["glyphs"][1])
    sf.seq("envicons", "extras", icons["extras"][0], length=icons["extras"][1])
    sf.seq("envlights", "lights", "env/lights.png", length=8, BlendMode="Additive")
    ff, starts = fire["fire"]
    sf.seq("svc-fire", "idle", ff, length=6, start=starts["stage2"], Tick=90)
    for n in ("stage1", "stage2", "stage3", "stage4"):
        sf.seq("svc-fire", n, ff, length=6, start=starts[n] or None, Tick=90)
    sf.seq("svc-fire", "heap", ff, length=4, start=starts["heap"], Tick=100)
    pf, _ = fire["pile"]
    for i, n in enumerate(("small", "medium", "large")):
        sf.seq("svc-pile", n, pf, length=1, start=i or None)
    sf.seq("svc-heli", "idle", heli["heli"], length=4, start=12, Tick=40)
    sf.seq("svc-heli", "fly", heli["heli"], length=4, Facings=-8, Tick=40)
    sf.seq("svc-heli", "fly-fire", heli["heli"], length=4, start=32, Facings=-8, Tick=40)
    sf.write()

    L.write_if_changed(os.path.join(L.ISO, "life", "README"), readme(S, people, icons, fire, fx_rows))
    return "%d vehicle images (+%d legacy names), %d people images, %d fx sheets, icons/fire/piles/heli" % (
        len(VEH.MODELS_ALL), len(VEH.LEGACY), len(people), len(fx_rows))
