"""iso_export_terrain.py - ART area `terrain`: tileset, terrain.png, animated water, snow and flood overlays.

Outputs
  tilesets/temperate.yaml           TileSize 64,32; template ids/sizes/categories/terrain types as genterrain wrote them
  bits/terrain/terrain.png          one 64x32 diamond per template, FrameSize/FrameAmount grid, frame i = templates()[i]
  bits/world/iso/terrain/water.png  animated water: 8 frames per water template (see iso_terrain_ids.water_templates)
  bits/world/iso/terrain/snow.png   winter version of every land template, full + light (envsnow/snow)
  bits/world/iso/terrain/flood.png  4 flood-water frames (envflood/flood)
  sequences/environment.yaml        envsnow, envflood, envwater

Frame mapping rule (terrain.png): frame i is the i-th entry of iso_terrain_ids.templates(), i.e. the same order
genterrain.py wrote (grass 1..6, meadow 10,11,18,19, rough 12..14,20..22, dirt 15,16, sand 17, water 100..107,
beach land 200+k, shore water 400+k). Each template has `Frames: i`, Size 1,1.
Water animation (envwater/water): frame = water_index * 8 + f; water_index = position in water_templates():
open water ids 100..107 -> 0..7, shore water 400+k -> 8+k.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import iso_export_lib as L  # noqa: E402
import iso_terrain_ids as ids  # noqa: E402

TILE_W, TILE_H = 64, 32
ANIM = 8
FLOOD_FRAMES = 4
SNOW_LIGHT = 0.55          # share of a light-snow tile covered by snow patches
SHEET_COLS = 16

HEADER = """Owned by the environment work package. Generated by tools/iso_export.py (area terrain).
Snow, flood and water overlays are 64x32 diamonds drawn with a TerrainSpriteLayer (offset 0, one frame per cell).
  envsnow/snow    winter version of every terrain template, opaque: frame = 2 * template frame (terrain.png index,
                  the template's `Frames`) + 0 full snow / 1 light (patchy) snow. Water templates are empty frames.
                  CitySnowOverlay picks full or light per 2x2-cell patch as the snow cover builds up and melts.
  envflood/flood  4 flood-water frames, one 8-frame water phase apart by 2 (CityFloodOverlay, FrameMs per frame).
  envwater/water  animated water: frame = water_index * 8 + f (f = 0..7). water_index: terrain template 100..107 ->
                  0..7, 400 + k (k = 0..45, shore water) -> 8 + k. CityWaterAnimation draws it over visible water cells."""


# ---------------------------------------------------------------- tile jobs (module-level for the fork pool)
def _static_job(job):
    import iso_terrain_tiles as T
    kind, a, b = job
    if kind == "grass":
        return T.grass_tile(a)
    if kind == "meadow":
        return T.meadow_tile(a)
    if kind == "rough":
        return T.rough_tile(a)
    if kind == "dirt":
        return T.dirt_tile(a)
    if kind == "sand":
        return T.sand_tile()
    if kind == "land":
        mask, corners = ids.SHORE_COMBOS[a]
        return T.shore_land_tile(mask, corners)
    raise ValueError(kind)


def _water_job(job):
    import iso_terrain_tiles as T
    kind, a, f = job
    if kind == "open":
        depth, variant = a
        return T.water_depth_tile(depth, variant, f)
    mask, corners = ids.SHORE_COMBOS[a]
    return T.shore_water_tile(mask, corners, f)


def _static_job_kw(kind, a, **kw):
    import iso_terrain_tiles as T
    if kind == "land":
        mask, corners = ids.SHORE_COMBOS[a]
        return T.shore_land_tile(mask, corners, **kw)
    if kind == "sand":
        return T.sand_tile(**kw)
    return {"grass": T.grass_tile, "meadow": T.meadow_tile, "rough": T.rough_tile, "dirt": T.dirt_tile}[kind](a, **kw)


def _snow_job(job):
    """(static terrain job or None, template frame index) -> (full snow, light snow) of that land template."""
    import iso_terrain_tiles as T
    sjob, index = job
    if sjob is None:
        return None
    kind, a, _b = sjob
    summer = _static_job(sjob)
    full = _static_job_kw(kind, a, season="winter")
    return full, T.light_snow(summer, full, SNOW_LIGHT, index)


def _overlay_job(job):
    import iso_terrain_tiles as T
    kind, a = job
    return T.snow_tile(a) if kind == "snow" else T.flood_tile(a)


def _open_water_spec(tid):
    """(depth, variant) of an open-water template id."""
    for depth, group in zip(("shallow", "open", "deep"), ids.WATER_IDS):
        if tid in group:
            return depth, group.index(tid)
    raise ValueError(tid)


def _check_ids():
    """The id scheme must stay what genterrain wrote (existing maps depend on it; verified equal against
    genterrain.py with a one-off script when the scheme moved to iso_terrain_ids.py)."""
    t = ids.templates()
    assert len({tid for tid, _ in t}) == len(t), "duplicate template ids"
    assert len(ids.SHORE_COMBOS) == 46
    assert (ids.LAND_BASE, ids.WATER_BASE) == (200, 400)
    assert [tid for tid, _ in t][:6] == [1, 2, 3, 4, 5, 6]


def write_tileset(tmpl):
    cats = {"Clear": "Terrain", "Rough": "Terrain", "Water": "Water"}
    out = ["General:", "\tName: tileset-temperate", "\tId: TEMPERATE", "\tTileSize: %d, %d" % (TILE_W, TILE_H),
           "\tSheetSize: 2048", "\tEditorTemplateOrder: Terrain, Water, Shore", "", "Terrain:"]
    for n, col, tt in (("Clear", "78B052", "Ground"), ("Rough", "7F9A52", "Ground"),
                       ("Water", "4A9FC9", "Water"), ("Road", "505050", "Ground")):
        out += ["\tTerrainType@%s:" % n, "\t\tType: %s" % n, "\t\tTargetTypes: %s" % tt, "\t\tColor: %s" % col]
    out += ["", "Templates:"]
    for i, (tid, tt) in enumerate(tmpl):
        cat = "Shore" if tid >= ids.LAND_BASE else cats[tt]
        out += ["\tTemplate@%d:" % tid, "\t\tId: %d" % tid, "\t\tImages: terrain.png", "\t\tFrames: %d" % i,
                "\t\tSize: 1,1", "\t\tCategories: %s" % cat, "\t\tTiles:", "\t\t\t0: %s" % tt]
    L.write_if_changed(os.path.join(ids.MOD, "tilesets", "temperate.yaml"), "\n".join(out) + "\n")


def write_terrain_png(imgs):
    n = len(imgs)
    rows = (n + SHEET_COLS - 1) // SHEET_COLS
    sheet = np.zeros((rows * TILE_H, SHEET_COLS * TILE_W, 4), np.uint8)
    for i, im in enumerate(imgs):
        r, c = divmod(i, SHEET_COLS)
        sheet[r * TILE_H:(r + 1) * TILE_H, c * TILE_W:(c + 1) * TILE_W] = im
    meta = [("FrameSize", "%d,%d" % (TILE_W, TILE_H)), ("FrameAmount", str(n))]
    L.write_if_changed(os.path.join(ids.MOD, "bits", "terrain", "terrain.png"), L.png_bytes(sheet, meta))


def _frame(spr):
    return L.Frame(spr.img, 32, 16)


def export():
    _check_ids()
    tmpl = ids.templates()

    # ---- static frames (terrain.png): water templates use frame 0 of their animation
    static_jobs, water_jobs = [], []
    for tid, _tt in tmpl:
        if tid in ids.GRASS_IDS:
            static_jobs.append(("grass", tid - 1, 0))
        elif tid in ids.MEADOW_IDS:
            static_jobs.append(("meadow", ids.MEADOW_IDS.index(tid), 0))
        elif tid in ids.ROUGH_IDS:
            static_jobs.append(("rough", ids.ROUGH_IDS.index(tid), 0))
        elif tid in ids.DIRT_IDS:
            static_jobs.append(("dirt", ids.DIRT_IDS.index(tid), 0))
        elif tid == ids.SAND_ID:
            static_jobs.append(("sand", 0, 0))
        elif ids.LAND_BASE <= tid < ids.LAND_BASE + len(ids.SHORE_COMBOS):
            static_jobs.append(("land", tid - ids.LAND_BASE, 0))
        else:
            static_jobs.append(None)       # water: filled from the animation below
    for tid in ids.water_templates():
        for f in range(ANIM):
            if tid in ids.OPEN_WATER_IDS:
                water_jobs.append(("open", _open_water_spec(tid), f))
            else:
                water_jobs.append(("shore", tid - ids.WATER_BASE, f))

    todo = [j for j in static_jobs if j is not None]
    done = iter(L.pmap(_static_job, todo))
    water = L.pmap(_water_job, water_jobs)
    wsprites = {tid: water[k * ANIM:(k + 1) * ANIM] for k, tid in enumerate(ids.water_templates())}

    imgs = []
    for (tid, _tt), job in zip(tmpl, static_jobs):
        imgs.append(next(done).img if job is not None else wsprites[tid][0].img)
    write_terrain_png(imgs)
    write_tileset(tmpl)

    # ---- animated water, snow, flood
    n_water = L.write_sheet("terrain/water.png", [_frame(s) for tid in ids.water_templates() for s in wsprites[tid]])
    snow = L.pmap(_snow_job, [(job, i) for i, job in enumerate(static_jobs)])
    snow_frames = []
    for pair in snow:
        snow_frames += [L.EMPTY, L.EMPTY] if pair is None else [_frame(pair[0]), _frame(pair[1])]
    n_snow = L.write_sheet("terrain/snow.png", snow_frames)
    flood = L.pmap(_overlay_job, [("flood", f * 2) for f in range(FLOOD_FRAMES)])
    n_flood = L.write_sheet("terrain/flood.png", [_frame(s) for s in flood])

    sf = L.SeqFile("environment.yaml", HEADER)
    sf.seq("envsnow", "snow", "iso/terrain/snow.png", length=n_snow)
    sf.seq("envflood", "flood", "iso/terrain/flood.png", length=FLOOD_FRAMES)
    sf.seq("envwater", "water", "iso/terrain/water.png", length=n_water)
    sf.write()

    if os.environ.get("ISO_EXPORT_PREVIEW"):
        L.preview("/tmp/terrain-static.png", [_frame(type("S", (), {"img": im})) for im in imgs], cols=16, k=3)
        L.preview("/tmp/terrain-water.png", [_frame(s) for tid in ids.water_templates()[:12] for s in wsprites[tid]], cols=8, k=3)
        L.preview("/tmp/terrain-overlays.png", snow_frames[:48] + [_frame(s) for s in flood], cols=8, k=4)
    return "%d terrain frames, water %d frames (%d templates x %d), snow %d, flood %d" % (
        len(imgs), n_water, len(ids.water_templates()), ANIM, n_snow, n_flood)
