#!/usr/bin/env python3
"""
uiexport - exports the OpenCity icon recipes as resolution independent vector drawing ops.

  python3 -B mods/city/tools/uiexport.py

The game draws all chrome at runtime (OpenRA.Mods.City/Graphics/Chrome, CityChromeGenerator) at the exact
device scale, so no pre-rendered 1x/2x/3x atlases are shipped. The icon *designs* still live here as python
recipes (uibaseglyphs.py); this script runs them against a recording canvas and writes the
primitive calls to mods/city/bits/chrome/cityicons.vec, which the C# generator replays.

Format (one op per line, coordinates in design units, colours RRGGBBAA, '-' = none):
  set <name>                     start an icon set (icons of the set share a design size)
  icon <name> <w> <h>            start an icon
  R x y w h r tl tr br bl fill stroke sw   rounded rect (tl..bl = per corner radii or '-')
  C cx cy r fill stroke sw       circle
  E cx cy rx ry fill             ellipse
  G cx cy r w col                ring (stroke-only circle of mid radius r)
  L x0 y0 x1 y1 w col cap        capsule line (cap 1) or butt line (cap 0)
  P col x0 y0 x1 y1 ...          polygon fill
  B x y w h col                  pixel-snapped rect
  alias <name> <target>          another name for an icon of the same set
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
MOD = os.path.dirname(HERE)
OUT = os.path.join(MOD, 'bits', 'chrome', 'cityicons.vec')

from uidraw import col  # noqa: E402


def num(v):
    s = ('%.3f' % v).rstrip('0').rstrip('.')
    return '0' if s in ('-0', '') else s


def colour(c):
    if c is None:
        return '-'
    if callable(c):
        raise ValueError('callable fills cannot be exported')
    c = col(c)
    return '%02X%02X%02X%02X' % tuple(int(v) for v in c)


class Recorder:
    """Duck-types uidraw.G: records the primitive calls instead of rasterizing them."""

    def __init__(self, w, h):
        self.s = 1
        self.dw, self.dh = w, h
        self.ops = []

    def rrect(self, x, y, w, h, r, fill=None, stroke=None, sw=1, rr=None):
        radii = ' '.join(num(v) for v in rr) if rr else '- - - -'
        self.ops.append('R %s %s %s %s %s %s %s %s %s' % (num(x), num(y), num(w), num(h), num(r), radii,
                                                         colour(fill), colour(stroke), num(sw)))

    def circle(self, cx, cy, r, fill=None, stroke=None, sw=1):
        self.ops.append('C %s %s %s %s %s %s' % (num(cx), num(cy), num(r), colour(fill), colour(stroke), num(sw)))

    def ellipse(self, cx, cy, rx, ry, fill):
        self.ops.append('E %s %s %s %s %s' % (num(cx), num(cy), num(rx), num(ry), colour(fill)))

    def ring(self, cx, cy, r, w, c):
        self.ops.append('G %s %s %s %s %s' % (num(cx), num(cy), num(r), num(w), colour(c)))

    def line(self, x0, y0, x1, y1, w, c, cap=True):
        self.ops.append('L %s %s %s %s %s %s %d' % (num(x0), num(y0), num(x1), num(y1), num(w), colour(c), 1 if cap else 0))

    def polyline(self, pts, w, c, closed=False):
        n = len(pts)
        for i in range(n - 1 + (1 if closed else 0)):
            a, b = pts[i], pts[(i + 1) % n]
            self.line(a[0], a[1], b[0], b[1], w, c)

    def arc(self, cx, cy, r, a0, a1, w, c):
        import math
        steps = max(6, int(abs(a1 - a0) / 8))
        pts = []
        for i in range(steps + 1):
            a = math.radians(a0 + (a1 - a0) * i / steps)
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
        self.polyline(pts, w, c)

    def poly(self, pts, c):
        self.ops.append('P %s %s' % (colour(c), ' '.join(num(v) for p in pts for v in p)))

    def rect(self, x, y, w, h, c):
        self.ops.append('B %s %s %s %s %s' % (num(x), num(y), num(w), num(h), colour(c)))


def export_set(lines, name, size, icons, aliases):
    lines.append('set %s' % name)
    for entry in icons:
        # (name, fn) uses the set's design size, (name, w, h, fn) its own
        n, w, h, fn = entry if len(entry) == 4 else (entry[0], size[0], size[1], entry[1])
        rec = Recorder(w, h)
        fn(rec)
        lines.append('icon %s %d %d' % (n, w, h))
        lines.extend(rec.ops)
    for a, t in sorted(aliases.items()):
        lines.append('alias %s %s' % (a, t))


def main():
    # The HUD icons are the RCT2 set (iso_ui_icons_*.py, exported as atlases by iso_ui_export.py); only the small
    # glyphs of the shared OpenRA dialogs are still vector recipes.
    lines = ['# GENERATED by tools/uiexport.py from the uibaseglyphs.py recipes - do not edit by hand.']
    try:
        import uibaseglyphs
    except ImportError:
        uibaseglyphs = None
    if uibaseglyphs is not None:
        export_set(lines, 'glyphs', (16, 16), uibaseglyphs.GLYPHS, getattr(uibaseglyphs, 'ALIASES', {}))
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('uiexport: %d lines -> %s' % (len(lines), os.path.relpath(OUT, MOD)))


if __name__ == '__main__':
    main()
