## Owned by the ui work package. See mods/city/CONTRACT.md.

## Main menu
label-city-tagline = Build your city
button-city-new = New City
button-city-load = Load City

## New city panel
label-newgame-title = Choose a Map
label-newgame-no-maps = No city maps found.
label-newgame-map-size = { $width } x { $height } cells
label-newgame-map-author = by { $author }
button-newgame-start = Start City

## In-game menu button
button-city-menu = Menu
button-city-menu-tooltip = Game menu

## Top bar
button-city-speed-pause-tooltip = Pause
button-city-speed-1-tooltip = Normal speed
button-city-speed-2-tooltip = Fast
button-city-speed-3-tooltip = Fastest
label-city-balance = { $balance }/month
label-city-milestone-bar = { $name }: { $population } / { $next }
label-city-milestone-max = { $name }: { $population }
label-city-stat-happiness = Happiness
label-city-stat-power = Power
label-city-stat-water = Water
label-city-power-bar = Power { $used } / { $produced }
label-city-water-bar = Water { $used } / { $produced }
label-city-percent = { $value }%

## Demand bars
label-demand-residential = Residential demand
label-demand-commercial = Commercial demand
label-demand-industrial = Industrial demand
label-demand-office = Office demand
label-demand-value = { $value }

## Toolbar
button-city-tool-road = Roads
button-city-tool-zoning = Zoning
button-city-tool-power = Electricity
button-city-tool-water = Water
button-city-tool-police = Police
button-city-tool-fire = Fire Department
button-city-tool-health = Health Care
button-city-tool-education = Education
button-city-tool-parks = Parks
button-city-tool-bulldoze = Bulldoze
button-city-tool-infoviews = Info Views
button-city-tool-budget = Budget

label-city-category-road = Roads
label-city-road-description = Cost: { $cost } per cell. Drag to build a road.
label-city-category-zoning = Zoning
label-city-category-power = Electricity
label-city-category-water = Water
label-city-category-police = Police
label-city-category-fire = Fire Department
label-city-category-health = Health Care
label-city-category-education = Education
label-city-category-parks = Parks

label-city-unlocks-at = Unlocks at { $population }
label-city-requires-population = Requires { $population } population
label-city-cost = Cost: { $cost }
label-city-cost-upkeep = Cost: { $cost }   Upkeep: { $upkeep }/month

## Zones
label-zone-res-low = Residential Low
label-zone-res-low-desc = Houses and small homes
label-zone-res-high = Residential High
label-zone-res-high-desc = Apartment blocks and towers
label-zone-com-low = Commercial Low
label-zone-com-low-desc = Shops and small stores
label-zone-com-high = Commercial High
label-zone-com-high-desc = Department stores and malls
label-zone-ind = Industrial
label-zone-ind-desc = Workshops and factories
label-zone-off = Office
label-zone-off-desc = Office blocks and glass towers
label-zone-dezone = Remove Zone
label-zone-dezone-desc = Clears zoning from the painted area

## Info views
label-infoviews-title = Info Views
label-infoviews-legend-low = Poor
label-infoviews-legend-high = Good
label-infoview-off = Off
label-infoview-off-desc = No overlay
label-infoview-power = Electricity
label-infoview-power-desc = Green: powered, red: no power
label-infoview-water = Water
label-infoview-water-desc = Green: has water, red: no water
label-infoview-landvalue = Land Value
label-infoview-landvalue-desc = Higher land value is greener
label-infoview-pollution = Pollution
label-infoview-pollution-desc = Pollution of the area, darker is worse
label-infoview-police = Police
label-infoview-police-desc = Police coverage
label-infoview-fire = Fire
label-infoview-fire-desc = Fire protection coverage
label-infoview-health = Health
label-infoview-health-desc = Health care coverage
label-infoview-education = Education
label-infoview-education-desc = Education coverage
label-infoview-parks = Parks
label-infoview-parks-desc = Park coverage
label-infoview-traffic = Traffic
label-infoview-traffic-desc = Red: congested roads, green: free flowing
label-infoview-happiness = Happiness
label-infoview-happiness-desc = Happiness of buildings

## Budget
label-budget-title = Budget
button-budget-close = Close
label-budget-income = Income (last month)
label-budget-expenses = Expenses (last month)
label-budget-total = Total: { $amount }
label-budget-balance = Monthly balance: { $balance }
label-budget-taxes = Tax rates
label-budget-tax-residential = Residential
label-budget-tax-commercial = Commercial
label-budget-tax-industrial = Industrial
label-budget-tax-office = Office
label-budget-upkeep-roads = Road upkeep
label-budget-upkeep-services = Service upkeep
label-budget-construction = Construction
label-budget-milestone = Milestone rewards
label-budget-refund = Refunds

## Building info
label-building-zone-level = { $zone }, level { $level }
label-building-status = Status
label-building-residents = Residents
label-building-jobs = Workers
label-building-power = Electricity
label-building-water = Water
label-building-road = Road access
label-building-happiness = Happiness
label-building-landvalue = Land value
label-building-upkeep = Upkeep
label-building-status-operational = Operational
label-building-status-construction = Under construction
label-building-status-abandoned = Abandoned
label-building-status-offline = Offline
label-building-connected = Connected
label-building-no-power = No power
label-building-no-water = No water
label-building-no-road = No road
label-building-current-of-max = { $current } / { $max }
label-building-per-month = { $amount }/month

## Info views (groups, legend, new views)
label-infoviews-legend-min = Low
label-infoviews-legend-max = High
label-infoview-group-services = Services
label-infoview-group-networks = Networks
label-infoview-group-environment = Environment
label-infoview-group-city = City
label-infoview-garbage = Garbage
label-infoview-garbage-desc = Garbage collection coverage
label-infoview-deathcare = Deathcare
label-infoview-deathcare-desc = Cemetery and crematorium coverage
label-infoview-crime = Crime
label-infoview-crime-desc = Red: high crime pressure, green: safe
label-infoview-crime-low = Safe
label-infoview-crime-high = Crime
label-infoview-telecom = Telecom
label-infoview-telecom-desc = Telecom coverage
label-infoview-post = Post
label-infoview-post-desc = Mail service coverage
label-infoview-powergrid = Power grid
label-infoview-powergrid-desc = Power supply of each building
label-infoview-watergrid = Water grid
label-infoview-watergrid-desc = Water supply of each building
label-infoview-sewage = Sewage
label-infoview-sewage-desc = Green: connected to sewage, red: no sewage
label-infoview-roads = Roads
label-infoview-roads-desc = Road classes: hover a road for lanes and speed
label-infoview-traffic-low = Free
label-infoview-traffic-high = Jammed
label-infoview-transit = Public transport
label-infoview-transit-desc = Stop coverage and line usage
label-infoview-freight = Freight
label-infoview-freight-desc = Truck load on roads
label-infoview-pollution-low = Clean
label-infoview-pollution-high = Polluted
label-infoview-air = Air pollution
label-infoview-air-desc = Air pollution of the area
label-infoview-ground = Ground pollution
label-infoview-ground-desc = Ground pollution of the area
label-infoview-noise = Noise
label-infoview-noise-desc = Noise from roads and buildings
label-infoview-groundwater = Groundwater
label-infoview-groundwater-desc = Polluted groundwater
label-infoview-resources = Natural resources
label-infoview-resources-desc = Yellow: fertile land, green: forest, blue: ore, dark: oil. Stronger is richer
label-infoview-landvalue-low = Low
label-infoview-landvalue-high = High
label-infoview-level = Building level
label-infoview-level-desc = Level of each building, 1 (red) to 5 (green)
label-infoview-level-low = Level 1
label-infoview-level-high = Level 5
label-infoview-attainment = Education level
label-infoview-attainment-desc = Average education of the residents
label-infoview-wealth = Wealth
label-infoview-wealth-desc = Average cash of the households
label-infoview-age = Age
label-infoview-age-desc = Average age of the residents
label-infoview-age-low = Young
label-infoview-age-high = Old
label-infoview-production = Production
label-infoview-production-desc = Stock fill of the companies
label-infoview-tourism = Tourism
label-infoview-tourism-desc = Attractiveness for tourists
label-infoview-districts = Districts
label-infoview-districts-desc = Each colour is a district
label-summary-produced = Produced
label-summary-used = Used
label-summary-capacity = Capacity
label-summary-flow = City traffic flow
label-summary-vehicles = Vehicles
label-summary-happiness = Average happiness
label-summary-health = Average health
label-summary-budget = Budget
label-roadclass-local = Local street
label-roadclass-collector = Collector
label-roadclass-arterial = Arterial
label-roadclass-highway = Highway
label-road-detail = { $lanes } lanes, speed { $speed }%, parking { $parking }
label-road-flow = Flow { $value }%

## Factor tooltips
label-factors-none = No factors

## Building info (additions)
label-building-level = Level
label-building-level-of = { $level } of 5
label-building-households = Households
label-building-students = Students
label-building-beds = Beds in use
label-building-company = Company
label-building-sewage = Sewage
label-building-no-sewage = No sewage
label-building-rent = Rent
label-building-tab-residents = Residents
label-building-tab-workers = Workers
label-building-happiness-title = Happiness { $value }% (city factors)

## Citizen panel
label-citizen-age-line = { $age }, { $years } years
label-citizen-education = Education
label-citizen-job = Job
label-citizen-school = School
label-citizen-home = Home
label-citizen-activity = Doing
label-citizen-happiness = Happiness
label-citizen-health = Health
label-citizen-cash = Household cash
label-citizen-unemployed = Unemployed
label-citizen-retired = Retired
label-citizen-homeless = Homeless
button-citizen-home = Home
button-citizen-work = Work

label-education-uneducated = Uneducated
label-education-poorly = Poorly educated
label-education-educated = Educated
label-education-well = Well educated
label-education-highly = Highly educated
label-age-child = Child
label-age-teen = Teen
label-age-adult = Adult
label-age-senior = Senior
label-activity-home = At home
label-activity-working = Working
label-activity-studying = Studying
label-activity-shopping = Shopping
label-activity-leisure = Leisure
label-activity-travelling = Travelling
label-activity-hospital = In hospital
label-activity-prison = In prison
label-activity-moving = Moving
label-activity-dead = Dead
label-kind-none = Building
label-kind-residential = Residential
label-kind-commercial = Commercial
label-kind-industrial = Industrial
label-kind-office = Office
label-kind-warehouse = Warehouse
label-kind-extractor = Extractor
label-kind-service = Service
label-kind-transit = Transit
label-kind-signature = Signature building

## Statistics
label-stats-title = City statistics
label-stats-now = Now
label-stats-months-ago = { $count } months ago
label-stats-empty = No statistics recorded yet.
button-stats-scale-year = 1 year
button-stats-scale-five = 5 years
button-stats-scale-all = All time
label-stats-category-population = Population
label-stats-category-economy = Economy
label-stats-category-city = City
label-stats-category-utilities = Utilities
label-stats-category-environment = Environment
label-stats-category-traffic = Traffic
label-stats-population = Population
label-stats-households = Households
label-stats-workers = Workers
label-stats-unemployed = Unemployed
label-stats-jobs = Jobs
label-stats-students = Students
label-stats-money = Money
label-stats-income = Income
label-stats-expenses = Expenses
label-stats-loan = Loan
label-stats-tax-residential = Residential tax
label-stats-tax-commercial = Commercial tax
label-stats-tax-industrial = Industrial tax
label-stats-tax-office = Office tax
label-stats-happiness = Happiness
label-stats-health = Health
label-stats-landvalue = Land value
label-stats-crime = Crime
label-stats-demand-r = Residential demand
label-stats-demand-c = Commercial demand
label-stats-demand-i = Industrial demand
label-stats-demand-o = Office demand
label-stats-power-produced = Power produced
label-stats-power-used = Power used
label-stats-water-produced = Water produced
label-stats-water-used = Water used
label-stats-pollution-ground = Ground pollution
label-stats-pollution-air = Air pollution
label-stats-pollution-noise = Noise
label-stats-traffic-flow = Traffic flow
label-stats-traffic-load = Traffic load
label-stats-vehicles = Vehicles
label-stats-transit-passengers = Transit passengers

## Chirper
label-chirper-title = Chirper
label-chirper-empty = Nothing to chirp about yet.
label-chirper-cityhall = City Hall
label-chirper-author-likes = { $name }   { $likes } likes
button-chirper-locate = Show on the map

## Budget (tabs, services, fees, loan)
label-budget-tab-budget = Budget
label-budget-tab-taxes = Taxes
label-budget-tab-services = Services
label-budget-tab-fees = Fees
label-budget-tab-loan = Loan
label-budget-trend-income = Income
label-budget-trend-expenses = Expenses
label-budget-tax-details = Details: { $name }
label-budget-tax-details-none = No details available.
label-budget-services = Service budgets
label-budget-services-hint = A higher budget raises capacity and upkeep. 100% is the default.
label-budget-service-value = { $budget }%  (eff. { $eff }%)
label-budget-fees = Fees
label-budget-fees-hint = Fees are a percentage of the default price. Higher fees earn more but lower happiness and efficiency.
label-budget-fee-power = Electricity
label-budget-fee-water = Water
label-budget-fee-garbage = Garbage
label-budget-fee-health = Health care
label-budget-fee-education = Education
label-budget-fee-parking = Parking
label-budget-loan = Loan
label-budget-loan-slider = Borrow
label-budget-loan-info = Loan { $principal } of { $limit }, interest { $rate }% per month
label-budget-loan-preview = Interest at this size: { $amount } per month
label-budget-loan-note = A bigger milestone raises your loan limit. Lowering the slider repays the loan.
label-budget-tax-income = Taxes
label-budget-fee-income = Fees
label-budget-loan-interest = Loan interest
label-budget-loan-repay = Loan repayment
label-budget-wages-services = Service wages
label-budget-import-services = Imported services
label-budget-export-services = Exported services
label-service-power = Electricity
label-service-water = Water
label-service-sewage = Sewage
label-service-garbage = Garbage
label-service-health = Health care
label-service-deathcare = Deathcare
label-service-education = Education
label-service-police = Police
label-service-fire = Fire department
label-service-parks = Parks
label-service-telecom = Telecom
label-service-post = Post
label-service-admin = Administration

## Tool tabs, road palette, new tools
button-city-tool-networks = Networks
button-city-tool-garbage = Garbage
button-city-tool-deathcare = Deathcare
button-city-tool-comms = Communications
button-city-tool-admin = Administration
button-city-tool-industry = Industry
button-city-tool-transit = Public transport
button-city-tool-stats = Statistics
button-city-tool-chirper = Chirper
button-city-tool-production = Production
button-city-tool-policies = Policies
button-city-tool-progression = Milestones and development
button-city-tool-districts = Districts
button-city-tool-tiles = Buy map tiles
label-city-category-networks = Networks
label-city-category-garbage = Garbage
label-city-category-deathcare = Deathcare
label-city-category-comms = Communications
label-city-category-admin = Administration
label-city-category-industry = Industry
label-city-category-transit = Public transport
label-city-cost-per-cell = { $cost } per cell
label-road-type-description = { $cost } per cell, upkeep { $upkeep }, { $lanes } lanes, speed { $speed }%
label-road-type-street = Street
label-road-type-gravel = Gravel road
label-road-type-avenue = Avenue
label-road-type-boulevard = Boulevard
label-road-type-highway = Highway
label-road-type-alley = Alley
label-road-mode-draw = Draw
label-road-mode-draw-desc = Build roads of the selected type
label-road-mode-oneway = One-way
label-road-mode-oneway-desc = Draw direction is the traffic direction. Tab flips it
label-road-mode-replace = Replace
label-road-mode-replace-desc = Change the type of existing roads in place
label-road-mode-control = Junction control
label-road-mode-control-desc = Click a junction to cycle yield, stop and traffic signal
label-road-mode-roundabout = Roundabout
label-road-mode-roundabout-desc = Place a roundabout on a junction
label-road-mode-interchange = Interchange
label-road-mode-interchange-desc = Place a highway interchange
label-zone-locked = Not unlocked yet
label-zone-res-row = Residential Row
label-zone-res-row-desc = Terraced houses
label-zone-res-med = Residential Medium
label-zone-res-med-desc = Mid-rise apartments
label-zone-res-mixed = Residential Mixed
label-zone-res-mixed-desc = Flats above shops
label-zone-res-lowrent = Low Rent Housing
label-zone-res-lowrent-desc = Cheap dense housing
label-zone-off-high = Office High
label-zone-off-high-desc = Office towers
label-zone-warehouse = Warehouse
label-zone-warehouse-desc = Storage and distribution
label-tool-powerline = Power line
label-tool-powerline-desc = Drag to lay a high voltage line
label-tool-pipe = Pipe
label-tool-pipe-desc = Drag to lay water and sewage pipes
label-tool-cells = cells
label-tool-cells-count = { $count } cells
label-tool-area-paint = Paint area
label-tool-area-paint-desc = Drag around the selected hub to add area
label-tool-area-clear = Clear area
label-tool-area-clear-desc = Drag to remove area from the selected hub
label-industry-select-hub = Select a hub first
label-tool-busstop = Bus stop
label-tool-busstop-desc = Place a bus stop on a road
label-tool-busline = Bus line
label-tool-busline-desc = Click stops in order, Enter or the first stop again to finish
label-transit-line-preview = { $stops } stops, { $cells } cells
label-tiles-price = Buy for { $price }
label-tiles-owned = Owned
label-tiles-unavailable = Not next to your land
label-tiles-no-permit = No permit available

## Production
label-production-title = Production and trade
label-production-resource = Resource
label-production-produced = Produced
label-production-consumed = Consumed
label-production-imported = Imported
label-production-exported = Exported
label-production-stock = Stock
label-production-balance = Surplus / deficit
label-production-chart = { $name }: last two years

## Policies
label-policies-title = Policies
label-policies-city = City
label-policies-district = District
label-policies-no-districts = No districts yet
label-policies-upkeep = { $amount }/month
label-policies-locked = Locked
label-policies-hint = Hover a policy for its effects. Policies cost upkeep every month.

## Milestones and development tree
label-progress-title = Milestones and development
label-progress-milestone = { $name }: { $xp } / { $next } XP
label-progress-milestone-max = { $name }: { $xp } XP
label-progress-points = Development points: { $points }
label-progress-permits = Map tile permits: { $permits }
label-progress-milestones = Milestones
label-progress-tree = Development tree
label-progress-node-cost = { $cost } points
label-progress-node-owned = Owned
label-progress-node-requires = Requires: { $names }
label-progress-node-points = Not enough development points
label-progress-hint = Hover a node for details. Buying a node unlocks buildings, roads and policies.

## Districts
label-districts-title = Districts
label-districts-hint = New, Paint and Erase work by dragging rectangles on the map.
button-districts-new = New
button-districts-paint = Paint
button-districts-erase = Erase
button-districts-delete = Delete
label-districts-population = Population
label-districts-households = Households
label-districts-jobs = Jobs
label-districts-happiness = Happiness
label-districts-landvalue = Land value

## Transit overview
label-transit-title = Public transport lines
label-transit-empty = No lines yet. Place stops and use the bus line tool.
label-transit-line-info = { $stops } stops, { $vehicles } vehicles, { $passengers } passengers
label-transit-profit = { $amount }/month
label-transit-ticket = Ticket price
label-transit-vehicles = Vehicles
label-transit-mode-bus = Bus
label-transit-mode-tram = Tram
label-transit-mode-metro = Metro
label-transit-mode-train = Train
button-transit-delete = Delete line

## Resources (names for the production panel and the farm hub selector)
label-resource-grain = Grain
label-resource-vegetables = Vegetables
label-resource-cotton = Cotton
label-resource-livestock = Livestock

## Top bar additions
label-city-happiness-title = Happiness { $value }%
label-city-progress-xp = XP { $xp } / { $next }
label-city-progress-points = Development points: { $points }
label-city-progress-permits = Map tile permits: { $permits }

label-road-mode-paired = Paired
label-road-mode-paired-desc = Build both directions as two separate carriageways

## Statistics overview
label-stats-category-overview = Overview
label-overview-age = Age groups
label-overview-education = Education
label-overview-city = Employment and housing
label-overview-workers = Workers
label-overview-unemployed = Unemployed
label-overview-students = Students
label-overview-homeless = Homeless
label-overview-tourists = Tourists
button-citizen-follow = Follow

## Integration additions
label-transit-line-name = Line { $id }
label-service-efficiency = Efficiency
label-service-satisfaction = Satisfaction
label-service-capacity = Capacity in use
label-service-fleet = Vehicles on the road
label-service-inactive = Status
label-service-inactive-value = Not working
label-hub-product = Product
label-hub-area = Area cells
label-hub-output = Output
label-hub-capacity = Capacity
label-hub-capacity-value = { $units } units per day
label-hub-months-left = Months of stock left
label-road-mode-roundabout-large = Large roundabout
label-road-mode-roundabout-large-desc = Place a large roundabout on a junction
label-road-mode-ramp = Highway ramp
label-road-mode-ramp-desc = Connect a highway to a road
label-road-mode-control-yield = Yield sign
label-road-mode-control-yield-desc = Click a junction to give way
label-road-mode-control-stop = Stop sign
label-road-mode-control-stop-desc = Click a junction to stop all arms
label-road-mode-control-signal = Traffic signal
label-road-mode-control-signal-desc = Click a junction to place traffic lights
label-road-mode-control-default = Default control
label-road-mode-control-default-desc = Click a junction to restore its default control
label-tool-pipe-water = Water pipe
label-tool-pipe-water-desc = Drag to lay water pipes
label-tool-pipe-sewage = Sewage pipe
label-tool-pipe-sewage-desc = Drag to lay sewage pipes
label-tool-pipe-both = Water and sewage pipe
label-tool-pipe-both-desc = Drag to lay both pipes at once
label-tool-powerline-remove = Remove power line
label-tool-powerline-remove-desc = Drag to remove high voltage lines
label-tool-pipe-remove = Remove pipes
label-tool-pipe-remove-desc = Drag to remove water and sewage pipes
label-tool-taxistand = Taxi stand
label-tool-taxistand-desc = Place a taxi stand on a road
label-tool-stop-remove = Remove stop
label-tool-stop-remove-desc = Click a stop to remove it

## Ledger categories reported by the simulation
label-budget-overdraft-interest = Overdraft interest
label-budget-service-budget-savings = Service budget savings
label-budget-service-upgrade = Service upgrades
label-budget-utility-upkeep = Utility upkeep
label-budget-imported-services = Imported services
label-budget-trade = Trade
label-budget-industry = Industry
label-budget-recycling = Recycling
label-budget-crime = Crime losses
label-budget-fares-bus = Bus fares
label-budget-transit-upkeep = Transit upkeep
label-budget-transit-construction = Transit construction
label-budget-upkeep-return = Upkeep returned
label-budget-upkeep-power = Power upkeep
label-budget-upkeep-water = Water upkeep
label-budget-upkeep-sewage = Sewage upkeep
label-budget-upkeep-garbage = Garbage upkeep
label-budget-upkeep-health = Health care upkeep
label-budget-upkeep-deathcare = Deathcare upkeep
label-budget-upkeep-education = Education upkeep
label-budget-upkeep-police = Police upkeep
label-budget-upkeep-fire = Fire department upkeep
label-budget-upkeep-parks = Parks upkeep
label-budget-upkeep-telecom = Telecom upkeep
label-budget-upkeep-post = Post upkeep
label-budget-upkeep-admin = Administration upkeep

## Resource kinds (natural resources info view)
label-resource-kind-fertile = Fertile land
label-resource-kind-forest = Forest
label-resource-kind-ore = Ore
label-resource-kind-oil = Oil
label-resource-kind-stone = Stone
label-resource-kind-fish = Fish
label-summary-shipments = Shipments in transit
label-summary-attractiveness = Attractiveness
label-summary-visitors = Visitor groups per month
label-summary-tourists = Tourists now
label-tool-metroline = Metro line
label-tool-metroline-desc = Click the metro stations in order, Enter or the first station again to finish

## Wave 2: alerts, advisor, achievements, tiles
label-alert-chip = { $name } x{ $count }
button-city-tool-achievements = Achievements
button-city-tool-advisor = Advisor
button-advisor-close = Close the advisor
button-advisor-previous = Previous
button-advisor-next = Next
label-advisor-step = Step { $current } of { $total }
label-advisor-done = You have the basics down
tutorial-road-title = Build a road
tutorial-road-text = Everything starts with a road. Draw one from the highway entry into the empty land; citizens, deliveries and buses all travel on it.
tutorial-road-hint = Roads tab (R), then drag on the map.
tutorial-zone-title = Zone the land
tutorial-zone-text = Paint zones along your road. Houses, shops and factories grow by themselves where there is demand; watch the R, C, I and O bars.
tutorial-zone-hint = Zoning tab (Z), pick a zone and drag next to the road.
tutorial-power-title = Provide electricity
tutorial-power-text = Buildings need power to be operational. Place a power plant or a wind turbine and connect it to the road network.
tutorial-power-hint = Electricity tab, then place a plant.
tutorial-water-title = Provide water
tutorial-water-text = Water towers and pumps keep your citizens healthy. Without water buildings are switched off and people move out.
tutorial-water-hint = Water tab, then place a water tower.
tutorial-people-title = Wait for your first citizens
tutorial-people-text = Once the buildings have power and water, citizens move in. Unemployed citizens want jobs: zone some commercial or industrial land too.
tutorial-people-hint = Watch the population in the top bar.
tutorial-services-title = Add city services
tutorial-services-text = Police, fire stations, clinics and schools keep your city safe and healthy. The info views show where a service covers.
tutorial-services-hint = The service tabs on the left of the build palette.
tutorial-budget-title = Check the budget
tutorial-budget-text = Taxes pay for upkeep. Open the budget to see income and expenses, set tax rates and service budgets, or take a loan.
tutorial-budget-hint = Budget button (F) in the top order row.
tutorial-infoviews-title = Use the info views
tutorial-infoviews-text = Info views colour the map to show power, water, traffic, pollution, land value and more. Hover the map for the exact value.
tutorial-infoviews-hint = Info views button (I) in the top order row.
tutorial-grow-title = Grow your city
tutorial-grow-text = Reach 250 citizens for the next milestone. Milestones unlock buildings, map tiles and development points for new options.
tutorial-grow-hint = Open the milestones panel (J) to see what comes next.
label-achievements-title = Achievements
label-achievements-summary = { $count } of { $total } unlocked
label-achievements-streak = ({ $streak } of { $months } months)
label-achievements-xp = { $xp } XP
label-tiles-title = Buy map tiles
label-tiles-count = { $owned } of { $total } owned
label-tiles-row-tiles = Tiles
label-tiles-row-permits = Permits
label-tiles-row-status = This tile
label-tiles-row-price = Price
label-tiles-row-upkeep = Upkeep change
label-tiles-row-land = Buildable land
label-tiles-row-resources = Resources
label-tiles-status-buyable = Can be bought
label-tiles-land = { $buildable } of { $total } cells
label-tiles-no-resources = None
label-tiles-no-funds = Not enough money
label-tiles-invalid = Outside the map
label-tiles-legend-owned = Owned
label-tiles-legend-buyable = Can buy
label-tiles-legend-locked = Locked
label-road-mode-bridge = Bridge
label-road-mode-bridge-desc = Span short stretches of water with a bridge (costs three times as much)
label-road-mode-addon-remove = Remove add-ons
label-road-mode-addon-remove-desc = While on, the add-on tools remove the add-on instead of building it
label-alert-wildfire = Wildfire
label-service-condition = Condition
label-service-districts = Serves districts
label-service-districts-all = All
label-advisor-title = Advisor
label-hub-clearcut = Clear-cut the forest
label-city-cost-per-stop = Cost: { $cost } per stop
label-tool-tramstop = Tram stop
label-tool-tramstop-desc = Place a tram stop on a road with tram track
label-tool-tramtrack = Tram track
label-tool-tramtrack-desc = Drag along roads to lay tram track
label-tool-tramtrack-remove = Remove tram track
label-tool-tramtrack-remove-desc = Drag to remove tram track
label-tool-rail = Rail track
label-tool-rail-desc = Drag to lay rail track (crossing roads needs level crossings)
label-tool-rail-remove = Remove rail track
label-tool-rail-remove-desc = Drag to remove rail track
label-tool-tramline = Tram line
label-tool-tramline-desc = Click the tram stops in order, Enter or the first stop again to finish
label-tool-trainline = Train line
label-tool-trainline-desc = Click the train stations in order, Enter or the first station again to finish
label-transit-line-cycle = { $seconds }s per round
label-transit-line-broken = route cut
label-alert-accident = Accident

## Vehicle card
label-vehicle-purpose = Trip
label-vehicle-mode = Mode
label-vehicle-from = From
label-vehicle-to = To
label-vehicle-driver = Driver
label-vehicle-status = Status
label-vehicle-crashed = Crashed, waiting for help
label-vehicle-driving = Driving
label-purpose-work = Commuting to work
label-purpose-school = Going to school
label-purpose-shopping = Shopping
label-purpose-leisure = Leisure
label-purpose-health = Seeing a doctor
label-purpose-goinghome = Going home
label-purpose-commute = Commuting
label-purpose-tourism = Sightseeing
label-purpose-freight = Freight
label-purpose-service = City service
label-purpose-emergency = Emergency
label-purpose-transit = Public transport
label-purpose-through = Passing through
label-travelmode-car = Car
label-travelmode-walk = On foot
label-travelmode-transit = Transit
label-travelmode-taxi = Taxi
label-travelmode-bike = Bicycle
label-travelmode-truck = Truck
label-travelmode-serviceVehicle = Service vehicle
label-travelmode-emergencyvehicle = Emergency vehicle
label-travelmode-bus = Bus
label-traffic-flow = Flow
label-traffic-volume = Volume
label-traffic-hour = { $hour }:00

## Signature buildings (palette tooltip)
label-signature-locked = Locked: { $progress }% of the requirements met
label-signature-ready = Ready to build. Only one per city.
label-signature-built = Built. Only one per city.
label-signature-rule-open = - { $rule }: { $have } / { $need }
label-signature-rule-met = + { $rule }: { $have } / { $need }
label-signature-rule-zonecells = { $target } district cells
label-signature-rule-level5count = Level 5 { $target } lots
label-signature-rule-happiness = Happiness
label-signature-rule-population = Population
label-signature-rule-milestone = Milestone reached
label-signature-rule-servicebuilt = { $target } built
label-signature-wellbeing = Well-being +{ $value } within { $radius } cells
label-signature-attractiveness = Tourist attractiveness +{ $value }
label-signature-efficiency = Efficiency +{ $value }%
label-signature-pollution = Pollution -{ $value }%

## Lot facts of the building inspector
label-lot-corner = Location
label-lot-corner-value = Corner lot
label-lot-rooms = Hotel rooms
label-lot-storage = Storage space
