## Zoning & growables
## Growable buildings
actor-res-low-1 =
    .name = Small House
actor-res-low-2 =
    .name = House
actor-res-low-3 =
    .name = Villa
actor-res-high-1 =
    .name = Apartment Block
actor-res-high-2 =
    .name = Apartment Building
actor-res-high-3 =
    .name = Residential Tower
actor-com-low-1 =
    .name = Corner Shop
actor-com-low-2 =
    .name = Store
actor-com-low-3 =
    .name = Supermarket
actor-com-high-1 =
    .name = Shopping Arcade
actor-com-high-2 =
    .name = Department Store
actor-com-high-3 =
    .name = Mall
actor-ind-1 =
    .name = Workshop
actor-ind-2 =
    .name = Factory
actor-ind-3 =
    .name = Industrial Plant
actor-off-1 =
    .name = Small Office
actor-off-2 =
    .name = Office Building
actor-off-3 =
    .name = Office Tower

## Lot archetypes (one actor per zone and footprint; the level is state on the actor)
actor-lot-res-low =
    .name = Low Density Housing
actor-lot-res-row =
    .name = Row Housing
actor-lot-res-med =
    .name = Medium Density Housing
actor-lot-res-high =
    .name = High Density Housing
actor-lot-res-lowrent =
    .name = Low Rent Housing
actor-lot-res-mixed =
    .name = Mixed Use Building
actor-lot-com-low =
    .name = Low Density Shops
actor-lot-com-high =
    .name = High Density Commerce
actor-lot-off =
    .name = Offices
actor-lot-off-high =
    .name = High Rise Offices
actor-lot-ind =
    .name = Industry
actor-lot-warehouse =
    .name = Warehouse
actor-rubble =
    .name = Rubble

## Signature buildings
actor-sig-villa =
    .name = Mayor's Villa
    .description = A landmark mansion. Raises well-being of the neighbourhood. Needs a large low density district and happy citizens.
actor-sig-garden-row =
    .name = Garden Row
    .description = Grand terraced villas with gardens. Raises well-being nearby. Needs a row housing district.
actor-sig-sky-tower =
    .name = Sky Tower
    .description = A supertall residential tower. Big well-being bonus. Needs several level 5 high density towers.
actor-sig-bazaar =
    .name = Grand Bazaar
    .description = A lively market hall that attracts tourists. Needs a large low density shopping district.
actor-sig-mall =
    .name = City Mall
    .description = A huge glass mall. Strong tourist attraction. Needs several level 5 high density shops.
actor-sig-glass-hub =
    .name = Glass Hub
    .description = A landmark office tower that makes offices more efficient. Needs level 5 offices and a school.
actor-sig-fuel-plant =
    .name = Fuel Plant
    .description = A clean industrial showpiece: more efficient industry, less pollution. Needs level 5 industry.
