## Services
actor-powerplant-coal =
    .name = Coal Power Plant
    .description = Produces lots of electricity, but pollutes the area around it.
actor-windturbine =
    .name = Wind Turbine
    .description = Clean, cheap electricity in small amounts.
actor-solarplant =
    .name = Solar Power Plant
    .description = Clean electricity for a growing city.
actor-watertower =
    .name = Water Tower
    .description = Supplies a small amount of fresh water.
actor-waterpump =
    .name = Water Pumping Station
    .description = Pumps large amounts of water. Must be built next to water.
actor-police =
    .name = Police Station
    .description = Reduces crime in the surrounding area.
actor-firestation =
    .name = Fire Station
    .description = Protects nearby buildings from fire.
actor-clinic =
    .name = Medical Clinic
    .description = Keeps nearby citizens healthy.
actor-school =
    .name = Elementary School
    .description = Educates children in the surrounding area.
actor-park-small =
    .name = Small Park
    .description = A patch of green that makes neighbours happier.
actor-plaza =
    .name = Plaza
    .description = A paved square with a fountain.
actor-park-large =
    .name = City Park
    .description = A large park that raises land value around it.

## City notifications
notification-city-milestone-1 = Milestone reached: Hamlet! $5,000 bonus and new buildings unlocked.
notification-city-milestone-2 = Milestone reached: Small Town! $10,000 bonus and new buildings unlocked.
notification-city-milestone-3 = Milestone reached: Town! $20,000 bonus and new buildings unlocked.
notification-city-milestone-4 = Milestone reached: Large Town! $40,000 bonus and new buildings unlocked.
notification-city-milestone-5 = Milestone reached: Small City! $60,000 bonus and new buildings unlocked.
notification-city-milestone-6 = Milestone reached: City! $100,000 bonus and new buildings unlocked.
notification-city-milestone-7 = Milestone reached: Metropolis! $200,000 bonus and new buildings unlocked.
notification-city-bankrupt = The city is out of money! Construction is blocked until funds are positive.

## Services work package: new buildings
actor-powerplant-gas =
    .name = Gas Power Plant
    .description = Reliable mid-sized electricity from natural gas. Pollutes moderately.
actor-hydro-dam =
    .name = Hydroelectric Dam
    .description = Clean electricity from flowing water. Must be built next to water.
actor-powerplant-nuclear =
    .name = Nuclear Power Plant
    .description = Huge amounts of electricity for a metropolis. Needs lots of water.
actor-waterpump-large =
    .name = Large Pumping Station
    .description = Pumps a very large amount of water. Must be built next to water.
actor-landfill =
    .name = Landfill
    .description = Stores the city's garbage. Garbage trucks drive from here to collect it.
actor-incinerator =
    .name = Incineration Plant
    .description = Burns garbage and produces some electricity.
actor-recycling =
    .name = Recycling Center
    .description = Processes garbage into materials and earns money.
actor-hospital =
    .name = Hospital
    .description = Many beds and ambulances for the whole city.
actor-cemetery =
    .name = Cemetery
    .description = Buries the dead. Hearses collect the bodies.
actor-crematorium =
    .name = Crematorium
    .description = Cremates the dead, a little at a time.
actor-highschool =
    .name = High School
    .description = Educates teenagers.
actor-college =
    .name = College
    .description = Higher education for teenagers and adults.
actor-university =
    .name = University
    .description = The highest level of education.
actor-policebox =
    .name = Police Box
    .description = A small post with one patrol car.
actor-police-hq =
    .name = Police Headquarters
    .description = A large police force with a big jail.
actor-prison =
    .name = Prison
    .description = Holds the inmates of police jails.
actor-firehouse =
    .name = Fire House
    .description = A small fire station with two fire engines.
actor-sportsfield =
    .name = Sports Field
    .description = A place to play that keeps citizens happy.
actor-postoffice =
    .name = Post Office
    .description = Collects and delivers the mail with vans.
actor-sortingcenter =
    .name = Sorting Center
    .description = Sorts the mail of the whole city.
actor-telecom-mast =
    .name = Radio Mast
    .description = Phone and data coverage for a small area.
actor-telecom-tower =
    .name = Telecom Tower
    .description = Phone and data coverage for a large area.
actor-cityhall =
    .name = City Hall
    .description = Reduces crime everywhere in the city.
actor-welfare =
    .name = Welfare Office
    .description = Cheers up unhappy citizens nearby and reduces crime.

## Services work package: upgrades
upgrade-exhaust-filter =
    .name = Exhaust Filter
    .description = Halves the air pollution of the plant.
upgrade-truck-depot =
    .name = Truck Depot
    .description = Adds more vehicles.
upgrade-recycling-unit =
    .name = Recycling Unit
    .description = Halves the ground pollution.
upgrade-extra-furnace =
    .name = Extra Furnace
    .description = Burns more garbage and makes more electricity.
upgrade-ambulance-depot =
    .name = Ambulance Depot
    .description = Adds more ambulances.
upgrade-extension-wing =
    .name = Extension Wing
    .description = Adds more capacity.
upgrade-beds-wing =
    .description = Adds 20 beds.
upgrade-trauma-center =
    .name = Trauma Center
    .description = More beds and better treatment.
upgrade-columbarium =
    .name = Columbarium
    .description = More room for the dead.
upgrade-hearse-garage =
    .name = Hearse Garage
    .description = Adds more hearses.
upgrade-school-wing =
    .name = Extension Wing
    .description = Adds more seats.
upgrade-seats-wing =
    .description = Adds more seats for students.
upgrade-library =
    .name = Library
    .description = Students graduate more often.
upgrade-police-garage =
    .name = Garage
    .description = Adds more patrol cars.
upgrade-cell-block =
    .name = Cell Block
    .description = Adds more jail cells.
upgrade-engine-bay =
    .name = Engine Bay
    .description = Adds more fire engines.
upgrade-van-depot =
    .name = Van Depot
    .description = Adds more mail vans.

## Services work package: notifications
notification-service-fire = A building is on fire!
notification-service-landfill-full = Garbage storage is full! Trucks cannot unload.
notification-service-crime = Crime is on the rise.
notification-service-no-hospital = Sick citizens have no hospital bed.
notification-service-body = Dead bodies are waiting to be collected.

## Services work package: service names (budget panel, info views)
label-service-power = Electricity
label-service-water = Water
label-service-sewage = Sewage
label-service-garbage = Garbage
label-service-health = Healthcare
label-service-deathcare = Deathcare
label-service-education = Education
label-service-police = Police
label-service-fire = Fire and Rescue
label-service-parks = Parks and Recreation
label-service-telecom = Telecommunications
label-service-post = Post
label-service-admin = Administration

## Services work package: chirper
chirp-service-fire-1 = Fire! Smoke is rising over a building. Where are the fire engines?
chirp-service-fire-2 = Something is burning down the street. Call the fire department!
chirp-service-fire-lost-1 = A building burnt to the ground. Nothing is left but rubble.
chirp-service-fire-lost-2 = The fire won. Another building is gone.
chirp-service-crime-1 = Somebody got robbed and the culprit got away.
chirp-service-crime-2 = Crime pays, it seems. The police came too late.
chirp-service-landfill-full = The landfill is full! Garbage trucks have nowhere to go.

actor-medevac-helipad =
    .name = Medical Helicopter Base
    .description = Helicopters fly patients to a hospital in a straight line when ambulances cannot.
actor-fire-helipad =
    .name = Fire Helicopter Base
    .description = Helicopters help fight fires when no fire engine can arrive.
actor-firewatch =
    .name = Firewatch Tower
    .description = Spots wildfires in the surrounding trees and puts them out.

chirp-service-wildfire-1 = Smoke over the trees: a wildfire has started!
chirp-service-wildfire-2 = The forest is on fire. Is anyone watching the woods?
chirp-service-lightning-1 = Lightning struck a building and set it on fire.
chirp-service-lightning-2 = A bolt from the storm hit a roof. Flames everywhere!
chirp-service-blackout-1 = A power plant burnt down. Expect blackouts.
chirp-service-blackout-2 = The lights went out: our power plant is on fire.
