## RCT2 UI strings: Building and vehicle inspectors, transit lines.

## Building inspector
label-inspect-tab-overview = Overview
label-inspect-tab-occupants = Occupants
label-inspect-tab-finances = Finances
label-inspect-tab-upkeep = Upkeep and upgrades
label-inspect-tab-efficiency = Efficiency
label-inspect-status = Status:
label-inspect-no-problems = No problems reported.
label-inspect-goto = Go to building
label-inspect-goto-desc = Centre the camera on this building.
label-inspect-infoview = Show info view
label-inspect-infoview-desc = Toggle the { $name } info view.
label-inspect-upgrades = Upgrades
label-inspect-upgrades-desc = Open the upgrades of this building.
label-inspect-districts = District restriction
label-inspect-districts-desc = Choose the districts this building serves.
label-inspect-patients = Patients
label-inspect-students = Students
label-inspect-residents = Residents
label-inspect-workers = Workers
label-inspect-happiness = Happiness
label-inspect-electricity = Electricity
label-inspect-staffing = Staffing
label-inspect-col-name = Name
label-inspect-col-age = Age
label-inspect-col-education = Education
label-inspect-no-occupants = Nobody lives or works here yet.
label-inspect-header-costs = Monthly costs
label-inspect-header-property = Property
label-inspect-header-supply = Supply and access
label-inspect-header-performance = Performance
label-inspect-header-budget = Service budget
label-inspect-header-upgrades = Upgrades
label-inspect-header-production = Production
label-inspect-upgrade-upkeep = Upgrades
label-inspect-total = Total
label-inspect-budget-desc = Applies to every { $name } building in the city.
label-inspect-upgrade-built = Built
label-inspect-upgrade-upkeep-desc = Adds { $amount } upkeep per month.
label-inspect-problem-staff = Understaffed
label-inspect-problem-unhappy = Unhappy

## Transit lines window
label-transit-window-title = Transit lines - { $mode }
label-transit-mode-taxi = Taxi
label-transit-col-line = Line
label-transit-col-name = Name
label-transit-col-stand = Taxi stand
label-transit-col-stops = Stops
label-transit-col-vehicles = Veh.
label-transit-col-usage = Load
label-transit-col-profit = Profit
label-transit-col-waiting = Waiting
label-transit-col-rides = Rides
label-transit-footer-lines = { $count } lines
label-transit-footer-stands = { $count } stands
label-transit-footer-vehicles = { $count } vehicles
label-transit-footer-waiting = { $count } waiting
label-transit-footer-passengers = { $count } / month
label-transit-footer-rides = { $count } rides / month
label-transit-income = Income
label-transit-upkeep = Upkeep
label-transit-show-on-map = Show on map
label-transit-edit = Edit line
label-transit-delete = Delete
label-transit-empty-mode = No { $mode } lines yet. Place stops, then use the line tool.
label-transit-empty-taxi = No taxi stands yet. Place a taxi stand on a road.
label-transit-stand-name = Taxi stand { $x }, { $y }
label-transit-stop-name = Stop { $id }

## Transit line window
label-transit-line-title = { $mode } line { $id }
label-transit-tab-route = Route
label-transit-tab-vehicles = Vehicles
label-transit-tab-passengers = Passengers
label-transit-name = Name
label-transit-colour = Colour
label-transit-route-header = Route: { $stops } stops, { $cells } cells
label-transit-depot-slots = of { $count } depot slots
label-transit-no-depot = no depot yet
label-transit-passengers = Passengers
label-transit-per-month = { $count } / month
label-transit-locate = Locate
label-transit-follow = Follow vehicle
label-transit-col-vehicle = Vehicle
label-transit-col-next = Next stop
label-transit-col-load = Load
label-transit-col-state = Status
label-transit-state-moving = Moving
label-transit-state-boarding = Boarding
label-transit-state-returning = To depot
label-transit-state-waiting = Waiting
label-transit-average-load = Average load { $value }%
label-transit-no-vehicles = No vehicles on this line yet.
label-transit-waiting-count = { $count } waiting
label-transit-vehicle-name = { $mode } { $id }
label-transit-header-riders = Riders
label-transit-header-money = Money this month
label-transit-header-busiest = Busiest stops
label-transit-this-month = This month
label-transit-last-month = Last month
label-transit-load-factor = Load factor
label-transit-waiting-now = Waiting now
label-transit-gave-up = Gave up waiting
